/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esrg.ventana;

import static esrg.ventana.Administrador.sesion_admin;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author ESRG
 */
public class AcercaDe extends javax.swing.JFrame {

    /**
     * Creates new form AcercaDe
     */
    public AcercaDe() {
        initComponents();
        
        setTitle("Data System | Acerca de");
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        lbl_title2.setText(Login.nombreUsuario);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon_wallpaper = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icon_wallpaper);

        ImageIcon logo = new ImageIcon("src/images/DS.png");
        Icon icon_logo = new ImageIcon(logo.getImage().getScaledInstance(lbl_logo.getWidth(), lbl_logo.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_logo.setIcon(icon_logo);
        
        ImageIcon img_laGeekipedia = new ImageIcon("src/images/geekipedia.png");
        Icon icon_laGeekipedia_Logo = new ImageIcon(img_laGeekipedia.getImage().getScaledInstance(lbl_laGeekipedia_logo.getWidth(), lbl_laGeekipedia_logo.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_laGeekipedia_logo.setIcon(icon_laGeekipedia_Logo);
        
        ImageIcon img_esrg = new ImageIcon("src/images/esrg.png");
        Icon icon_esrg_Logo = new ImageIcon(img_esrg.getImage().getScaledInstance(lbl_esrg_logo.getWidth(), lbl_esrg_logo.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_esrg_logo.setIcon(icon_esrg_Logo);
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        lbl_title2 = new javax.swing.JLabel();
        lbl_laGeekipediaDeErnesto = new javax.swing.JLabel();
        lbl_laGeekipedia_contacto = new javax.swing.JLabel();
        lbl_laGeekipedia_logo = new javax.swing.JLabel();
        lbl_esrg_logo = new javax.swing.JLabel();
        lbl_esrg = new javax.swing.JLabel();
        lbl_agradecimiento = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Acerca del sistema");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 300, -1));
        getContentPane().add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 140));

        lbl_title2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_title2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title2.setText("Usuario");
        getContentPane().add(lbl_title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 300, -1));

        lbl_laGeekipediaDeErnesto.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lbl_laGeekipediaDeErnesto.setForeground(new java.awt.Color(0, 0, 255));
        lbl_laGeekipediaDeErnesto.setText("Sistema creado por el canal de YouTube: La Geekipdia de Ernesto");
        getContentPane().add(lbl_laGeekipediaDeErnesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 460, 30));

        lbl_laGeekipedia_contacto.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_laGeekipedia_contacto.setForeground(new java.awt.Color(0, 0, 204));
        lbl_laGeekipedia_contacto.setText("YouTube: La Geekipedia De Ernedto: Facebook / Twitter / Instagram");
        getContentPane().add(lbl_laGeekipedia_contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 400, 30));
        getContentPane().add(lbl_laGeekipedia_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 60, 60));
        getContentPane().add(lbl_esrg_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 100, 60));

        lbl_esrg.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lbl_esrg.setForeground(new java.awt.Color(137, 0, 0));
        lbl_esrg.setText("Sistema desarrollado por: ESRG.es");
        getContentPane().add(lbl_esrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 250, 30));

        lbl_agradecimiento.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_agradecimiento.setForeground(new java.awt.Color(137, 0, 0));
        lbl_agradecimiento.setText("En agradecimiento a Ernesto por su labor educativa.");
        getContentPane().add(lbl_agradecimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 310, 30));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcercaDe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_agradecimiento;
    private javax.swing.JLabel lbl_esrg;
    private javax.swing.JLabel lbl_esrg_logo;
    private javax.swing.JLabel lbl_laGeekipediaDeErnesto;
    private javax.swing.JLabel lbl_laGeekipedia_contacto;
    private javax.swing.JLabel lbl_laGeekipedia_logo;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title2;
    private javax.swing.JLabel lbl_wallpaper;
    // End of variables declaration//GEN-END:variables
}
