package esrg.ventana;

import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author ESRG
 */
public class Administrador extends javax.swing.JFrame {

    public static boolean sesion_admin;
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();

        setTitle("Data System | Administrador");
        setResizable(false);
        setLocationRelativeTo(null);
        lbl_footer.setText(Login.footer);

        sesion_admin = true;

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon_wallpaper = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icon_wallpaper);

        ImageIcon logo = new ImageIcon("src/images/DS.png");
        Icon icon_logo = new ImageIcon(logo.getImage().getScaledInstance(lbl_logo.getWidth(), lbl_logo.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_logo.setIcon(icon_logo);
        
        ImageIcon cerrarSesion = new ImageIcon("src/images/cerrar_sesion.png");
        Icon icon_singoff = new ImageIcon(cerrarSesion.getImage().getScaledInstance(100, 80, Image.SCALE_DEFAULT));
        bttn_creatividad.setIcon(icon_singoff);

        lbl_username.setText("Bienvenido " + Login.nombreUsuario);

        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        bttn_informacion = new javax.swing.JButton();
        bttn_capturista = new javax.swing.JButton();
        bttn_tecnico = new javax.swing.JButton();
        bttn_creatividad = new javax.swing.JButton();
        bttn_acercade = new javax.swing.JButton();
        bttn_agregarUsuario = new javax.swing.JButton();
        lbl_gestionarUsuario = new javax.swing.JLabel();
        lbl_capturista = new javax.swing.JLabel();
        lbl_tecnico = new javax.swing.JLabel();
        lbl_creatividad = new javax.swing.JLabel();
        lbl_acercade = new javax.swing.JLabel();
        lbl_agregarUsuario = new javax.swing.JLabel();
        lbl_footer = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        lbl_estatus = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_username.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("Hola");
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 390, -1));

        bttn_informacion.setBackground(new java.awt.Color(63, 84, 147));
        bttn_informacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationuser.png"))); // NOI18N
        bttn_informacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_informacionActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 120, 100));

        bttn_capturista.setBackground(new java.awt.Color(63, 84, 147));
        bttn_capturista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capturista.png"))); // NOI18N
        bttn_capturista.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_capturista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_capturistaActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_capturista, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 120, 100));

        bttn_tecnico.setBackground(new java.awt.Color(63, 84, 147));
        bttn_tecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tecnico.png"))); // NOI18N
        bttn_tecnico.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_tecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_tecnicoActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_tecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 120, 100));

        bttn_creatividad.setBackground(new java.awt.Color(63, 84, 147));
        bttn_creatividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar_sesion.png"))); // NOI18N
        bttn_creatividad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_creatividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_creatividadActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_creatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 120, 100));

        bttn_acercade.setBackground(new java.awt.Color(63, 84, 147));
        bttn_acercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/geekipedia.png"))); // NOI18N
        bttn_acercade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_acercadeActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_acercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 120, 100));

        bttn_agregarUsuario.setBackground(new java.awt.Color(63, 84, 147));
        bttn_agregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addUser.png"))); // NOI18N
        bttn_agregarUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_agregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_agregarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_agregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 120, 100));

        lbl_gestionarUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_gestionarUsuario.setForeground(new java.awt.Color(63, 84, 147));
        lbl_gestionarUsuario.setText("Gestionar usuario");
        getContentPane().add(lbl_gestionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 290, 130, -1));

        lbl_capturista.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_capturista.setForeground(new java.awt.Color(63, 84, 147));
        lbl_capturista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_capturista.setText("Capturista");
        getContentPane().add(lbl_capturista, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 120, -1));

        lbl_tecnico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_tecnico.setForeground(new java.awt.Color(63, 84, 147));
        lbl_tecnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tecnico.setText("Técnico");
        getContentPane().add(lbl_tecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 120, -1));

        lbl_creatividad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_creatividad.setForeground(new java.awt.Color(63, 84, 147));
        lbl_creatividad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_creatividad.setText("Cerrar sesión");
        getContentPane().add(lbl_creatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 120, -1));

        lbl_acercade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_acercade.setForeground(new java.awt.Color(63, 84, 147));
        lbl_acercade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_acercade.setText("Acerca de");
        getContentPane().add(lbl_acercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 120, -1));

        lbl_agregarUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_agregarUsuario.setForeground(new java.awt.Color(63, 84, 147));
        lbl_agregarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_agregarUsuario.setText("Agregar usuario");
        getContentPane().add(lbl_agregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 120, -1));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 480, 630, -1));
        getContentPane().add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 140));

        lbl_estatus.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_estatus.setForeground(new java.awt.Color(255, 255, 255));
        lbl_estatus.setText("Administrador");
        getContentPane().add(lbl_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_tecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_tecnicoActionPerformed
        new Tecnico().setVisible(true);
    }//GEN-LAST:event_bttn_tecnicoActionPerformed

    private void bttn_agregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_agregarUsuarioActionPerformed
        new RegistroUsuario().setVisible(true);
    }//GEN-LAST:event_bttn_agregarUsuarioActionPerformed

    private void bttn_creatividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_creatividadActionPerformed

        Frame[] todasLasVentanas = Frame.getFrames();

        for (Frame frame : todasLasVentanas) {
            if (frame instanceof JFrame && frame.isVisible()) {
                frame.dispose();
            }
        }

        Login login = new Login();
        login.setVisible(true);
       
    }//GEN-LAST:event_bttn_creatividadActionPerformed

    private void bttn_informacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_informacionActionPerformed
        new GestionarUsuario().setVisible(true);
    }//GEN-LAST:event_bttn_informacionActionPerformed

    private void bttn_capturistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_capturistaActionPerformed
        new Capturista().setVisible(true);
    }//GEN-LAST:event_bttn_capturistaActionPerformed

    private void bttn_acercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_acercadeActionPerformed
        new AcercaDe().setVisible(true);
    }//GEN-LAST:event_bttn_acercadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_acercade;
    private javax.swing.JButton bttn_agregarUsuario;
    private javax.swing.JButton bttn_capturista;
    private javax.swing.JButton bttn_creatividad;
    private javax.swing.JButton bttn_informacion;
    private javax.swing.JButton bttn_tecnico;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_acercade;
    private javax.swing.JLabel lbl_agregarUsuario;
    private javax.swing.JLabel lbl_capturista;
    private javax.swing.JLabel lbl_creatividad;
    private javax.swing.JLabel lbl_estatus;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_gestionarUsuario;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_tecnico;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_wallpaper;
    // End of variables declaration//GEN-END:variables
}
