package esrg.ventana;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Font;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.FileOutputStream;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
import java.util.Calendar;

import java.sql.*;

import clases.Conexion;
import com.itextpdf.text.DocumentException;
import java.io.IOException;

/**
 *
 * @author ESRG
 */
public class Capturista extends javax.swing.JFrame {

    /**
     * Creates new form Capturista
     */
    public Capturista() {
        initComponents();

        setLocationRelativeTo(null);
        setTitle("Data System | Capturista");
        setResizable(false);
        lbl_footer.setText(Login.footer);
        
        if(Login.tipoNivel.equals("Administrador")){
            lbl_creatividad.setText("Cerrar");
        } else {
            lbl_creatividad.setText("Cerrar sesión");
        }

        if (Administrador.sesion_admin == true) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon_wallpaper = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icon_wallpaper);

        ImageIcon logo = new ImageIcon("src/images/DS.png");
        Icon icon_icon = new ImageIcon(logo.getImage().getScaledInstance(lbl_logo.getWidth(), lbl_logo.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_logo.setIcon(icon_icon);

        ImageIcon cerrarsesion = new ImageIcon("src/images/cerrar_sesion.png");
        Icon icon_signoff = new ImageIcon(cerrarsesion.getImage().getScaledInstance(100, 80, Image.SCALE_DEFAULT));
        bttn_creatividad.setIcon(icon_signoff);

        lbl_username.setText("Bienvenido " + Login.nombreUsuario);
        lbl_nivel.setText(Login.tipoNivel);

        this.repaint();

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_username = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        lbl_nivel = new javax.swing.JLabel();
        bttn_addCliente = new javax.swing.JButton();
        bttn_gestionarCliente = new javax.swing.JButton();
        bttn_imprimir = new javax.swing.JButton();
        lbl_footer = new javax.swing.JLabel();
        lbl_addCliente = new javax.swing.JLabel();
        lbl_gestionarCliente = new javax.swing.JLabel();
        lbl_imprimir = new javax.swing.JLabel();
        bttn_creatividad = new javax.swing.JButton();
        bttn_acercade = new javax.swing.JButton();
        lbl_creatividad = new javax.swing.JLabel();
        lbl_acercade = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_username.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("Hola");
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 390, -1));
        getContentPane().add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 140));

        lbl_nivel.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_nivel.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nivel.setText("Capturista");
        getContentPane().add(lbl_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        bttn_addCliente.setBackground(new java.awt.Color(63, 84, 147));
        bttn_addCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addUser.png"))); // NOI18N
        bttn_addCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_addCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_addClienteActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_addCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 120, 100));

        bttn_gestionarCliente.setBackground(new java.awt.Color(63, 84, 147));
        bttn_gestionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationuser.png"))); // NOI18N
        bttn_gestionarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_gestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_gestionarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_gestionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 120, 100));

        bttn_imprimir.setBackground(new java.awt.Color(63, 84, 147));
        bttn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        bttn_imprimir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_imprimirActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 120, 100));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 630, -1));

        lbl_addCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_addCliente.setForeground(new java.awt.Color(63, 84, 147));
        lbl_addCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addCliente.setText("Añadir cliente");
        getContentPane().add(lbl_addCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 120, -1));

        lbl_gestionarCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_gestionarCliente.setForeground(new java.awt.Color(63, 84, 147));
        lbl_gestionarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_gestionarCliente.setText("Gestionar cliente");
        getContentPane().add(lbl_gestionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 140, -1));

        lbl_imprimir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_imprimir.setForeground(new java.awt.Color(63, 84, 147));
        lbl_imprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_imprimir.setText("Imprimir clientes");
        getContentPane().add(lbl_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 120, -1));

        bttn_creatividad.setBackground(new java.awt.Color(63, 84, 147));
        bttn_creatividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar_sesion.png"))); // NOI18N
        bttn_creatividad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_creatividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_creatividadActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_creatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 120, 100));

        bttn_acercade.setBackground(new java.awt.Color(63, 84, 147));
        bttn_acercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/geekipedia.png"))); // NOI18N
        bttn_acercade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_acercadeActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_acercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 120, 100));

        lbl_creatividad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_creatividad.setForeground(new java.awt.Color(63, 84, 147));
        lbl_creatividad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_creatividad.setText("Cerrar sesión");
        getContentPane().add(lbl_creatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 120, -1));

        lbl_acercade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_acercade.setForeground(new java.awt.Color(63, 84, 147));
        lbl_acercade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_acercade.setText("Acerca de");
        getContentPane().add(lbl_acercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 120, -1));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 640, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_addClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_addClienteActionPerformed
        new RegistroCliente().setVisible(true);
    }//GEN-LAST:event_bttn_addClienteActionPerformed

    private void bttn_gestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_gestionarClienteActionPerformed
        new GestionarCliente().setVisible(true);
    }//GEN-LAST:event_bttn_gestionarClienteActionPerformed

    private void bttn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_imprimirActionPerformed
        Document documento = new Document();
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Clientes.pdf"));

            com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src/images/BannerPDF.jpg");
            header.scaleToFit(620, 1000);
            header.setAlignment(Chunk.ALIGN_CENTER);

            Paragraph parrafo = new Paragraph();
            parrafo.setAlignment(Paragraph.ALIGN_LEFT);
            parrafo.setFont(FontFactory.getFont("Arial", 14, Font.NORMAL, BaseColor.BLACK));
            Calendar fecha = Calendar.getInstance();
            parrafo.add("Fecha: " + fecha.get(Calendar.DATE) + "/" + (fecha.get(Calendar.MONTH) + 1) + "/" + fecha.get(Calendar.YEAR) + "\n"
                    + "\nInforme que presenta la base de clientes vigentes con sus datos esenciales para la consulta y gestión. \n ");

            PdfPTable tabla = new PdfPTable(5);
            tabla.addCell("ID");
            tabla.addCell("Nombre");
            tabla.addCell("Email");
            tabla.addCell("Teléfono");
            tabla.addCell("Dirección");

            try {
                Connection cn = Conexion.conexion();
                PreparedStatement ps = cn.prepareStatement(
                        "select * from clientes");

                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    do {
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));
                        tabla.addCell(rs.getString(5));
                    } while (rs.next());
                }

                cn.close();

            } catch (SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error en la base de datos. Contacte con el administrador");
                System.out.println(" err");
            }

            documento.open();

            documento.add(header);
            documento.add(parrafo);
            documento.add(tabla);

            documento.close();

            javax.swing.JOptionPane.showMessageDialog(null, "Reporte creado correctamente.");

        } catch (DocumentException | IOException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error al crear reporte.");
        }
    }//GEN-LAST:event_bttn_imprimirActionPerformed

    private void bttn_creatividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_creatividadActionPerformed

        if (!Login.tipoNivel.equals("Administrador")) {

            Frame[] ventanas = Frame.getFrames();

            for (Frame frame : ventanas) {
                if (frame instanceof JFrame && frame.isVisible()) {
                    frame.dispose();
                }
            }

            Login login = new Login();
            login.setVisible(true);
            
        } else {
            dispose();
        }

    }//GEN-LAST:event_bttn_creatividadActionPerformed

    private void bttn_acercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_acercadeActionPerformed
        new AcercaDe().setVisible(true);
    }//GEN-LAST:event_bttn_acercadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Capturista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_acercade;
    private javax.swing.JButton bttn_addCliente;
    private javax.swing.JButton bttn_creatividad;
    private javax.swing.JButton bttn_gestionarCliente;
    private javax.swing.JButton bttn_imprimir;
    private javax.swing.JLabel lbl_acercade;
    private javax.swing.JLabel lbl_addCliente;
    private javax.swing.JLabel lbl_creatividad;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_gestionarCliente;
    private javax.swing.JLabel lbl_imprimir;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nivel;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_wallpaper;
    // End of variables declaration//GEN-END:variables
}
