/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esrg.ventana;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

import java.sql.*;
import clases.Conexion;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author ESRG
 */
public class GestionarCliente extends javax.swing.JFrame {
    
    DefaultTableModel model = new DefaultTableModel();
    public static int table_update;

    /**
     * Creates new form GestionarCliente
     */
    public GestionarCliente() {
        initComponents();
        
        setTitle("Data System | Gestionar cliente");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        lbl_footer.setText(Login.footer);
        
        ImageIcon img_wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon_wallpaper = new ImageIcon(img_wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), 
                lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icon_wallpaper);      
        
        ImageIcon icon = new ImageIcon("src/images/informationuser.png");
        Icon iconEscala = new ImageIcon(icon.getImage().getScaledInstance(lbl_icon.getWidth(), lbl_icon.getHeight(), Image.SCALE_DEFAULT));
        lbl_icon.setIcon(iconEscala);
        
        lbl_sesionPor.setText("Sesión de " + Login.username);
        
        this.repaint();
        
        try {
            
            Connection conexion = Conexion.conexion();
            PreparedStatement ps = conexion.prepareStatement(
                    "select id_cliente, nombre_cliente, email_cliente, tel_cliente, ultima_modificacion from clientes");
            ResultSet rs = ps.executeQuery();
            
            tbl_client = new JTable(model);
            scpclient.setViewportView(tbl_client);
            
            model.addColumn("ID");
            model.addColumn("Nombre");
            model.addColumn("Email");
            model.addColumn("Télefono");
            model.addColumn("Modificado");
                                                                                                                      
            while(rs.next()){
                Object [] filaEscrita = new Object[5];  
                for (int i = 0; i < 5; i++) {
                    filaEscrita[i] = rs.getObject(i + 1);
                }
                model.addRow(filaEscrita);
            }
            
            conexion.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error de conexión.");
            System.err.println("Error " + e);
        }
        
        tbl_client.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                int fila_point = tbl_client.rowAtPoint(e.getPoint());
                int columna_point = 0;
                
                if(fila_point > -1){
                    table_update = (int) model.getValueAt(fila_point, columna_point);
                    //JOptionPane.showMessageDialog(null, "el id del cliente seleccionando es: " + table_update);
                    new InformacionCliente().setVisible(true);
                }
            }
        });
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();
        lbl_sesionPor = new javax.swing.JLabel();
        scpclient = new javax.swing.JScrollPane();
        tbl_client = new javax.swing.JTable();
        lbl_footer = new javax.swing.JLabel();
        bttn_update = new javax.swing.JButton();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Gestionar cliente");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
        getContentPane().add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 80));

        lbl_sesionPor.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_sesionPor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sesionPor.setText("Sesión de ");
        getContentPane().add(lbl_sesionPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        scpclient.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 0, 1));

        tbl_client.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbl_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpclient.setViewportView(tbl_client);

        getContentPane().add(scpclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 580, 300));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 600, -1));

        bttn_update.setBackground(new java.awt.Color(63, 84, 147));
        bttn_update.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bttn_update.setForeground(new java.awt.Color(255, 255, 255));
        bttn_update.setText("Actualizar");
        bttn_update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 580, 20));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 503));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_updateActionPerformed
        for (int i = 0; i < tbl_client.getRowCount(); i++) {
            model.removeRow(i);
            i-=1;
        }
 
        try {
            Connection cn = Conexion.conexion();
            PreparedStatement ps = cn.prepareStatement(
                    "select id_cliente, nombre_cliente, email_cliente, tel_cliente, ultima_modificacion from clientes");
            
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Object [] filas = new Object[5];
                for (int i = 0; i < 5; i++) {
                    filas[i] = rs.getObject(i+1);
                }
                model.addRow(filas);
            }
            
            cn.close();
        } catch (SQLException er) {
            System.err.println("Error: " + er);
        }
    }//GEN-LAST:event_bttn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_update;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_sesionPor;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JScrollPane scpclient;
    private javax.swing.JTable tbl_client;
    // End of variables declaration//GEN-END:variables
}
