/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esrg.ventana;

import javax.swing.table.DefaultTableModel;

import java.sql.*;

import clases.Conexion;
import static esrg.ventana.GestionarCliente.table_update;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author ESRG
 */
public class GestionarEquipo extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    public static int table_update;

    /**
     * Creates new form GestionarEquipo
     */
    public GestionarEquipo() {
        initComponents();

        setTitle("Data System | Gestionar equipos");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        lbl_footer.setText(Login.footer);

        ImageIcon img_wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon_wallpaper = new ImageIcon(img_wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(),
                lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icon_wallpaper);

        ImageIcon icon = new ImageIcon("src/images/apoyo-tecnico.png");
        Icon iconEscala = new ImageIcon(icon.getImage().getScaledInstance(lbl_icon.getWidth(), lbl_icon.getHeight(), Image.SCALE_DEFAULT));
        lbl_icon.setIcon(iconEscala);

        lbl_sesionPor.setText("Sesión de " + Login.username);

        this.repaint();

        try {

            Connection conexion = Conexion.conexion();
            PreparedStatement ps = conexion.prepareStatement(
                    "select id_equipo, tipo_equipo, marca, estatus from equipos");
            ResultSet rs = ps.executeQuery();

            tbl_equipo = new JTable(model);
            scp_equipo.setViewportView(tbl_equipo);

            model.addColumn("ID");
            model.addColumn("Tipo");
            model.addColumn("Marca");
            model.addColumn("Estatus");

            while (rs.next()) {
                Object[] filaEscrita = new Object[4];
                for (int i = 0; i < 4; i++) {
                    filaEscrita[i] = rs.getObject(i + 1);
                }
                model.addRow(filaEscrita);
            }

            conexion.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error de conexión.");
            System.err.println("Error " + e);
        }

        searchFilter();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();
        lbl_sesionPor = new javax.swing.JLabel();
        scp_equipo = new javax.swing.JScrollPane();
        tbl_equipo = new javax.swing.JTable();
        lbl_footer = new javax.swing.JLabel();
        bttn_update = new javax.swing.JButton();
        cmb_estatus = new javax.swing.JComboBox<>();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Gestionar equipos");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
        getContentPane().add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 80));

        lbl_sesionPor.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_sesionPor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sesionPor.setText("Sesión de ");
        getContentPane().add(lbl_sesionPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        scp_equipo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 0, 1));

        tbl_equipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbl_equipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scp_equipo.setViewportView(tbl_equipo);

        getContentPane().add(scp_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 580, 280));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 600, -1));

        bttn_update.setBackground(new java.awt.Color(63, 84, 147));
        bttn_update.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bttn_update.setForeground(new java.awt.Color(255, 255, 255));
        bttn_update.setText("Actualizar");
        bttn_update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 580, 20));

        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nuevo ingreso", "No reparado", "En revisión", "Reparado", "Entregado" }));
        cmb_estatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_estatusActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 580, 20));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_updateActionPerformed
        updateTable();
    }//GEN-LAST:event_bttn_updateActionPerformed

    private void cmb_estatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_estatusActionPerformed

        for (int i = 0; i < tbl_equipo.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }

        String selection = cmb_estatus.getSelectedItem().toString();
        String query = "";

        if (selection.equals("Todos")) {
            query = "select id_equipo, tipo_equipo, marca, estatus from equipos";
        } else {
            query = "select id_equipo, tipo_equipo, marca, estatus from equipos where estatus = '" + selection + "'";
        }

        try {
            Connection cn = Conexion.conexion();
            PreparedStatement ps = cn.prepareStatement(query);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                do {
                    Object fila[] = new Object[4];
                    for (int i = 0; i < 4; i++) {
                        fila[i] = rs.getObject(i + 1);
                    }
                    model.addRow(fila);
                } while (rs.next());
            }

            cn.close();

        } catch (SQLException e) {
            System.err.println("Error " + e);
        }
    }//GEN-LAST:event_cmb_estatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_update;
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_sesionPor;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JScrollPane scp_equipo;
    private javax.swing.JTable tbl_equipo;
    // End of variables declaration//GEN-END:variables

    public void updateTable() {
        for (int i = 0; i < tbl_equipo.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }

        try {
            Connection cn = Conexion.conexion();
            PreparedStatement ps = cn.prepareStatement(
                    "select id_equipo, tipo_equipo, marca, estatus from equipos");

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Object[] filas = new Object[4];
                for (int i = 0; i < 4; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                model.addRow(filas);
            }

            cn.close();
        } catch (SQLException er) {
            System.err.println("Error: " + er);
        }
    }

    public void searchFilter() {
        tbl_equipo.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = tbl_equipo.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    table_update = (int) model.getValueAt(fila_point, columna_point);
                    //JOptionPane.showMessageDialog(null, "el id del cliente seleccionando es: " + table_update);
                    new InformacionEquipoTecnico().setVisible(true);
                }
            }
        });
    }
}
