/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esrg.ventana;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author ESRG
 */
public class GraficaMarcas extends javax.swing.JFrame {
    
    int acer, alienware, apple, asus, brother, dell, hp, lenovo, samsung, toshiba, xerox, total;
    String marca_nombre [] = new String[11];
    int marca_cantidad [] = new int [11];

    /**
     * Creates new form GraficaMarcas
     */
    public GraficaMarcas() {
        initComponents();
        
        setTitle("DataSystem | Gráfica de marcas");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        lbl_title2.setText("Sesión de " + Login.username);
        lbl_footer.setText(Login.footer);
        
        ImageIcon img_wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon wallpaper = new ImageIcon(img_wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(wallpaper);
        
        ImageIcon img_logo = new ImageIcon("src/images/grafica.png");
        Icon logo = new ImageIcon(img_logo.getImage().getScaledInstance(lbl_icono.getWidth(), lbl_icono.getHeight(), Image.SCALE_DEFAULT));
        lbl_icono.setIcon(logo);
        
        this.getData();
        
        repaint();
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_title2 = new javax.swing.JLabel();
        lbl_footer = new javax.swing.JLabel();
        lbl_icono = new javax.swing.JLabel();
        bttn_update = new javax.swing.JButton();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Gráfica de marcas");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 390, -1));

        lbl_title2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_title2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title2.setText("Sesión de...");
        getContentPane().add(lbl_title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 400, -1));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 560, -1));
        getContentPane().add(lbl_icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 80));

        bttn_update.setBackground(new java.awt.Color(63, 84, 147));
        bttn_update.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bttn_update.setForeground(new java.awt.Color(255, 255, 255));
        bttn_update.setText("Actualizar");
        bttn_update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 520, 40));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_updateActionPerformed
        getData();
        repaint();
    }//GEN-LAST:event_bttn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficaMarcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_update;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_icono;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title2;
    private javax.swing.JLabel lbl_wallpaper;
    // End of variables declaration//GEN-END:variables

    private void getData(){
        try {
            Connection cn = Conexion.conexion();
            PreparedStatement ps = cn.prepareStatement("select marca, count(estatus) as Cantidad from equipos group by marca");
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                int indice = 0;
                
                do {
                    marca_nombre [indice] = rs.getString(1);
                    marca_cantidad [indice] = rs.getInt(2);
                    
                    if(marca_nombre[indice].equalsIgnoreCase("Acer")){
                        acer = marca_cantidad[indice];
                        
                    } else if(marca_nombre[indice].equalsIgnoreCase("Alienware")){
                        alienware = marca_cantidad[indice];
                        
                    } else if(marca_nombre[indice].equalsIgnoreCase("Apple")){
                        apple = marca_cantidad[indice];
                        
                    } else if(marca_nombre[indice].equalsIgnoreCase("Asus")){
                        asus = marca_cantidad[indice];
                        
                    } else if(marca_nombre[indice].equalsIgnoreCase("Brother")){
                        brother = marca_cantidad[indice];
                        
                    } else if(marca_nombre[indice].equalsIgnoreCase("Dell")){
                        dell = marca_cantidad[indice];
                        
                    } else if(marca_nombre[indice].equalsIgnoreCase("Hp")){
                        hp = marca_cantidad[indice];
                        
                    } else if(marca_nombre[indice].equalsIgnoreCase("Lenovo")){
                        lenovo = marca_cantidad[indice];
                        
                    } else if(marca_nombre[indice].equalsIgnoreCase("Samsung")){                        
                        samsung = marca_cantidad[indice];
                        
                    } else if(marca_nombre[indice].equalsIgnoreCase("Toshiba")){                        
                        toshiba = marca_cantidad[indice];
                        
                    } else if(marca_nombre[indice].equalsIgnoreCase("Xerox")){
                        xerox = marca_cantidad[indice];
                    } 
                    
                    indice++;
                    
                } while (rs.next());
            }
        } catch (SQLException er) {
            System.out.println("Error:  " + er);
        }
    }
    
    public void paint(Graphics g){
        super.paint(g);
        
        total = acer + alienware + apple + asus + brother + dell + hp + lenovo + samsung + toshiba + xerox;
        
        double grado1 = acer * 360.0 / total;
        double grado2 = alienware * 360.0 / total;  
        double grado3 = apple * 360.0 / total;
        double grado4 = asus * 360.0 / total;
        double grado5 = brother * 360.0 / total;
        double grado6 = dell * 360.0 / total;
        double grado7 = hp * 360.0 / total;
        double grado8 = lenovo * 360.0 / total;
        double grado9 = samsung * 360.0 / total;
        double grado10 = toshiba * 360.0 / total;
        double grado11 = xerox * 360.0 / total;
        
        int por1 = (int) Math.round(grado1);
        int por2 = (int) Math.round(grado2); 
        int por3 = (int) Math.round(grado3); 
        int por4 = (int) Math.round(grado4); 
        int por5 = (int) Math.round(grado5); 
        int por6 = (int) Math.round(grado6); 
        int por7 = (int) Math.round(grado7); 
        int por8 = (int) Math.round(grado8); 
        int por9 = (int) Math.round(grado9); 
        int por10 = (int) Math.round(grado10); 
        int por11 = (int) Math.round(grado11); 
        
        g.setColor(new Color(153,153,153));
        g.fillRect(350,190,15,15);
        g.drawString("Acer: " + acer, 380, 202);
        g.fillArc(60, 180, 225, 225, 0, por1);
        
        g.setColor(new Color(255,255,0));
        g.fillRect(350,210,15,15);
        g.drawString("Alienware: " + alienware, 380, 222);
        g.fillArc(60, 180, 225, 225, por1, por2);
        
        g.setColor(new Color(102,255,0));
        g.fillRect(350,230,15,15);
        g.drawString("Apple: " + apple, 380, 242);
        g.fillArc(60, 180, 225, 225, (por1 + por2), por3);
        
        g.setColor(new Color(204,0,255));
        g.fillRect(350,250,15,15);
        g.drawString("Asus: " + asus, 380, 262);
        g.fillArc(60, 180, 225, 225, (por1 + por2 + por3), por4);
        
        g.setColor(new Color(153,51,0));
        g.fillRect(350,270,15,15);
        g.drawString("Brother: " + brother, 380, 282);
        g.fillArc(60, 180, 225, 225, (por1 + por2 + por3 + por4), por5);
        
        g.setColor(new Color(102,0,204));
        g.fillRect(350,290,15,15);
        g.drawString("Dell: " + dell, 380, 302);
        g.fillArc(60, 180, 225, 225, (por1 + por2 + por3 + por4 + por5), por6);
        
        g.setColor(new Color(51,51,0));
        g.fillRect(350,310,15,15);
        g.drawString("HP: " + hp, 380, 322);
        g.fillArc(60, 180, 225, 225, (por1 + por2 + por3 + por4 + por5 + por6), por7);
        
        g.setColor(new Color(255,102,0));
        g.fillRect(350,330,15,15);
        g.drawString("Lenovo: " + lenovo, 380, 342);
        g.fillArc(60, 180, 225, 225, (por1 + por2 + por3 + por4 + por5 + por6 + por7), por8);
        
        g.setColor(new Color(0,0,51));
        g.fillRect(350,350,15,15);
        g.drawString("Samsung: " + samsung, 380, 362);
        g.fillArc(60, 180, 225, 225, (por1 + por2 + por3 + por4 + por5 + por6 + por7 + por8), por9);
        
        g.setColor(new Color(0,51,0));
        g.fillRect(350,370,15,15);
        g.drawString("Toshiba: " + toshiba, 380, 382);
        g.fillArc(60, 180, 225, 225, (por1 + por2 + por3 + por4 + por5 + por6 + por7 + por8 + por9), por10);
        
        g.setColor(new Color(51,0,153));
        g.fillRect(350,390,15,15);
        g.drawString("Xerox: " + xerox, 380, 402);
        g.fillArc(60, 180, 225, 225, (por1 + por2 + por3 + por4 + por5 + por6 + por7 + por8 + por9 + por10), por11);

    }            
}
