/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esrg.ventana;

import javax.swing.ImageIcon;
import javax.swing.Icon;
import java.awt.Image;
import java.awt.Graphics;
import java.awt.Color;

import java.sql.*;

import clases.Conexion;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author ESRG
 */
public class GraficaEstatus extends javax.swing.JFrame {

    int nuevoIngreso, noReparado, enRevision, reparado, entregado;
    String estatus_nombre [] = new String [5];
    int estatus_cantidad [] = new int [5];

    /**
     * Creates new form GraficaEstatus
     */
    public GraficaEstatus() {
        initComponents();
        
        setTitle("DataSystem | Gráfica de estatus");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        lbl_title2.setText("Sesión de " + Login.username);
        lbl_footer.setText(Login.footer);
        
        ImageIcon img_wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon wallpaper = new ImageIcon(img_wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(wallpaper);
        
        ImageIcon img_logo = new ImageIcon("src/images/grafica.png");
        Icon logo = new ImageIcon(img_logo.getImage().getScaledInstance(lbl_icono.getWidth(), lbl_icono.getHeight(), Image.SCALE_DEFAULT));
        lbl_icono.setIcon(logo);
        
        getData();
        
        repaint();

    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_title2 = new javax.swing.JLabel();
        lbl_footer = new javax.swing.JLabel();
        lbl_icono = new javax.swing.JLabel();
        bttn_update3 = new javax.swing.JButton();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Gráfica de estatus");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 390, -1));

        lbl_title2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_title2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title2.setText("Sesión de...");
        getContentPane().add(lbl_title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 530, -1));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 690, -1));
        getContentPane().add(lbl_icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 80));

        bttn_update3.setBackground(new java.awt.Color(63, 84, 147));
        bttn_update3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bttn_update3.setForeground(new java.awt.Color(255, 255, 255));
        bttn_update3.setText("Actualizar");
        bttn_update3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttn_update3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_update3ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_update3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 650, 40));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_update3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_update3ActionPerformed
        getData();
        repaint();
    }//GEN-LAST:event_bttn_update3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficaEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficaEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficaEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficaEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficaEstatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_update3;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_icono;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title2;
    private javax.swing.JLabel lbl_wallpaper;
    // End of variables declaration//GEN-END:variables

    private void getData(){
        try {
            Connection cn = Conexion.conexion();
            PreparedStatement ps = cn.prepareStatement("select estatus, count(estatus) as Cantidad from equipos group by estatus");
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                int indice = 0;
                
                do {
                    estatus_nombre [indice] = rs.getString(1);
                    estatus_cantidad [indice] = rs.getInt(2);
                    
                    if(estatus_nombre[indice].equalsIgnoreCase("Nuevo ingreso")){
                        nuevoIngreso = estatus_cantidad[indice];
                        
                    } else if(estatus_nombre[indice].equalsIgnoreCase("No reparado")){
                        noReparado = estatus_cantidad[indice];
                        
                    } else if(estatus_nombre[indice].equalsIgnoreCase("En revisión")){
                        enRevision = estatus_cantidad[indice];
                        
                    } else if(estatus_nombre[indice].equalsIgnoreCase("Reparado")){
                        reparado = estatus_cantidad[indice];
                        
                    } else if(estatus_nombre[indice].equalsIgnoreCase("Entregado")){
                        entregado = estatus_cantidad[indice];
                    }
                    
                    indice++;
                    
                } while (rs.next());
            }
        } catch (SQLException er) {
            System.out.println("Error:  " + er);
        }
    }

    public int mayorCantidad(int nuevoIngreso, int noReparado, int enRevision, int reparado, int entregado) {
        if (nuevoIngreso > noReparado && nuevoIngreso > enRevision && nuevoIngreso > reparado && nuevoIngreso > entregado) {
            return nuevoIngreso;
        } else if (noReparado > enRevision && noReparado > reparado && noReparado > entregado) {
            return noReparado;
        } else if (enRevision > reparado && enRevision > entregado) {
            return enRevision;
        } else if (reparado > entregado) {
            return reparado;
        } else {
            return entregado;
        }                
    }
    
    public void paint(Graphics g){
        super.paint(g);
        
        int mayor = mayorCantidad(nuevoIngreso, noReparado, enRevision, reparado, entregado);
        
        int barra1 = 0;
        int barra2 = 0;
        int barra3 = 0;
        int barra4 = 0;
        int barra5 = 0;

        try {
            barra1 = nuevoIngreso * 550 / mayor;
            barra2 = noReparado * 550 / mayor;
            barra3 = enRevision * 550 / mayor;
            barra4 = reparado * 550 / mayor;
            barra5 = entregado * 550 / mayor;
        } catch (Exception e) {}
        
        g.setColor(new Color(255,255,255));
        g.drawString("Nuevo ingreso", 30, 210);       
        g.drawString("Cantidad: " + nuevoIngreso, 30, 225); 
        g.fillRect(120, 200, barra1, 30);
        
        g.setColor(new Color(240,248,0));
        g.drawString("No raparado", 30, 260);       
        g.drawString("Cantidad: " + noReparado, 30, 275);
        g.fillRect(120, 250, barra2, 30);
        
        g.setColor(new Color(0,0,0));
        g.drawString("En revisión", 30, 310);       
        g.drawString("Cantidad: " + enRevision, 30, 325);
        g.fillRect(120, 300, barra3, 30);
        
        g.setColor(new Color(255,0,0));
        g.drawString("Reparado", 30, 360);       
        g.drawString("Cantidad: " + reparado, 30, 375);
        g.fillRect(120, 350, barra4, 30);
        
        g.setColor(new Color(0,85,0));
        g.drawString("Entregado", 30, 410);       
        g.drawString("Cantidad: " + entregado, 30, 425);
        g.fillRect(120, 400, barra5, 30);
    }
}
