/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esrg.ventana;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import clases.Conexion;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ESRG
 */
public class InformacionEquipoTecnico extends javax.swing.JFrame {

    /**
     * Creates new form InformacionEquipoTecnico
     */
    public InformacionEquipoTecnico() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Data System | Información de equipo");
        lbl_footer.setText(Login.footer);
                
        if(!Login.tipoNivel.equals("Administrador")){
            txt_reporteCapturista.setEditable(false);
            txt_reporteCapturista.setCaretColor(Color.white);
        } else {
            txt_reporteCapturista.setEditable(true);
            txt_reporteCapturista.setCaretColor(Color.black);
        }
        fld_fecha.setCaretColor(Color.white);
        fld_marca.setCaretColor(Color.white);
        fld_modelo.setCaretColor(Color.white);
        fld_numeroSerie.setCaretColor(Color.white);
        fld_tipoEquipo.setCaretColor(Color.white);
                      
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon iconoWallpaper = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(iconoWallpaper);
        
        ImageIcon image_icon = new ImageIcon("src/images/apoyo-tecnico.png");
        Icon icono = new ImageIcon(image_icon.getImage().getScaledInstance(lbl_icono.getWidth(), lbl_icono.getHeight(), Image.SCALE_DEFAULT));
        lbl_icono.setIcon(icono);
        
        repaint();
        
        lbl_title2.setText("ID del equipo: " + GestionarEquipo.table_update);
        lbl_ModificadoPor.setText("Modificado por: " + Login.username);
        try {
            Connection cn = Conexion.conexion();
            PreparedStatement ps = cn.prepareStatement("select * from equipos where id_equipo = '" + GestionarEquipo.table_update + "'");
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                fld_fecha.setText(rs.getString("dia_ingreso") + "/" + rs.getString("mes_ingreso") + "/" + rs.getString("annio_ingreso"));
                fld_marca.setText(rs.getString("marca"));
                fld_modelo.setText(rs.getString("modelo"));
                fld_numeroSerie.setText(rs.getString("num_serie"));
                fld_tipoEquipo.setText(rs.getString("tipo_equipo"));                
                txt_reporteCapturista.setText(rs.getString("observaciones"));
                lbl_reporteTecnico.setText("Reporte del técnico: " + rs.getString("revision_tecnica_de"));
                txt_reporteTecnico.setText(rs.getString("comentarios_tecnicos"));  
                
                if(Login.tipoNivel.equals("Administrador")) {
                    cmb_estatus.addItem("Entregado");
                    cmb_estatus.setSelectedItem(rs.getString("estatus"));                
                }else if(!rs.getString("estatus").equals("Entregado")){
                    cmb_estatus.setSelectedItem(rs.getString("estatus"));                
                }else {
                    cmb_estatus.addItem("Entregado");
                    cmb_estatus.setSelectedItem("Entregado");
                    cmb_estatus.setEnabled(false);
                }
            }
            
            cn.close();
            
        } catch(SQLException er){
            System.err.println("Error: " + er);
        }
        
        if(cmb_estatus.getSelectedItem().equals("Entregado") && !Login.tipoNivel.equals("Administrador")){
            bttn_actualizarEquipo.setEnabled(false);
        }
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_icono = new javax.swing.JLabel();
        lbl_title1 = new javax.swing.JLabel();
        lbl_title2 = new javax.swing.JLabel();
        lbl_tipoEquipo = new javax.swing.JLabel();
        fld_tipoEquipo = new javax.swing.JTextField();
        lbl_marca = new javax.swing.JLabel();
        fld_marca = new javax.swing.JTextField();
        lbl_reporteTecnico = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_reporteTecnico = new javax.swing.JTextPane();
        lbl_reporteCapturista = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_reporteCapturista = new javax.swing.JTextPane();
        bttn_actualizarEquipo = new javax.swing.JButton();
        lbl_modelo2 = new javax.swing.JLabel();
        lbl_numeroSerie1 = new javax.swing.JLabel();
        fld_modelo = new javax.swing.JTextField();
        fld_numeroSerie = new javax.swing.JTextField();
        lbl_ModificadoPor = new javax.swing.JLabel();
        lbl_modelo3 = new javax.swing.JLabel();
        fld_fecha = new javax.swing.JTextField();
        lbl_estatus1 = new javax.swing.JLabel();
        cmb_estatus = new javax.swing.JComboBox<>();
        lbl_footer = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lbl_icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 80));

        lbl_title1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title1.setText("Información de equipo");
        getContentPane().add(lbl_title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        lbl_title2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_title2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title2.setText("ID del equipo: ");
        getContentPane().add(lbl_title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        lbl_tipoEquipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_tipoEquipo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipoEquipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_tipoEquipo.setText("Tipo Equipo");
        getContentPane().add(lbl_tipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 180, -1));

        fld_tipoEquipo.setEditable(false);
        fld_tipoEquipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_tipoEquipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_tipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 180, 20));

        lbl_marca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_marca.setForeground(new java.awt.Color(255, 255, 255));
        lbl_marca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_marca.setText("Marca");
        getContentPane().add(lbl_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 180, -1));

        fld_marca.setEditable(false);
        fld_marca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_marca.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 180, 20));

        lbl_reporteTecnico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_reporteTecnico.setForeground(new java.awt.Color(255, 255, 255));
        lbl_reporteTecnico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_reporteTecnico.setText("Comentarios y actualización del técnico");
        getContentPane().add(lbl_reporteTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 390, -1));

        jScrollPane2.setEnabled(false);
        jScrollPane2.setViewportView(txt_reporteTecnico);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 390, 120));

        lbl_reporteCapturista.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_reporteCapturista.setForeground(new java.awt.Color(255, 255, 255));
        lbl_reporteCapturista.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_reporteCapturista.setText("Daño reportado y observaciones");
        getContentPane().add(lbl_reporteCapturista, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 240, -1));

        txt_reporteCapturista.setEditable(false);
        jScrollPane3.setViewportView(txt_reporteCapturista);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 390, 120));

        bttn_actualizarEquipo.setBackground(new java.awt.Color(63, 84, 147));
        bttn_actualizarEquipo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bttn_actualizarEquipo.setForeground(new java.awt.Color(255, 255, 255));
        bttn_actualizarEquipo.setText("Actualizar estado");
        bttn_actualizarEquipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttn_actualizarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_actualizarEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_actualizarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 390, 30));

        lbl_modelo2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_modelo2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_modelo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_modelo2.setText("Modelo");
        getContentPane().add(lbl_modelo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 180, -1));

        lbl_numeroSerie1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_numeroSerie1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_numeroSerie1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_numeroSerie1.setText("Número de serie");
        getContentPane().add(lbl_numeroSerie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 180, -1));

        fld_modelo.setEditable(false);
        fld_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_modelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 180, 20));

        fld_numeroSerie.setEditable(false);
        fld_numeroSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_numeroSerie.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_numeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 180, 20));

        lbl_ModificadoPor.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lbl_ModificadoPor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ModificadoPor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_ModificadoPor.setText("Modificado por:");
        getContentPane().add(lbl_ModificadoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 390, -1));

        lbl_modelo3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_modelo3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_modelo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_modelo3.setText("Fecha de ingreso");
        getContentPane().add(lbl_modelo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 180, -1));

        fld_fecha.setEditable(false);
        fld_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_fecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, 20));

        lbl_estatus1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_estatus1.setForeground(new java.awt.Color(102, 102, 255));
        lbl_estatus1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_estatus1.setText("Estatus");
        getContentPane().add(lbl_estatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 180, -1));

        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo ingreso", "No reparado", "En revisión", "Reparado" }));
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 180, -1));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 780, -1));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 580));
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_actualizarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_actualizarEquipoActionPerformed
       String estatus = cmb_estatus.getSelectedItem().toString();
       String comentario = txt_reporteCapturista.getText().trim();
       
       if(comentario.equals("")){
           comentario = "Sin observaciones.";
       } 
       
        try {
            Connection cn = Conexion.conexion();
            PreparedStatement ps = cn.prepareStatement(
                    "update equipos set estatus = ?, comentarios_tecnicos = ?, revision_tecnica_de = ? where id_equipo = '" + GestionarEquipo.table_update + "'");
            
            ps.setString(1, estatus);
            ps.setString(2, comentario);
            ps.setString(3, Login.nombreUsuario);
            
            ps.executeUpdate();
            
            cn.close();
            JOptionPane.showMessageDialog(null, "Estado actualizado correctamente.");
            
            dispose();
            
        } catch (SQLException e) {
            System.err.println("Error " + e);
        }
    }//GEN-LAST:event_bttn_actualizarEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionEquipoTecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_actualizarEquipo;
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JTextField fld_fecha;
    private javax.swing.JTextField fld_marca;
    private javax.swing.JTextField fld_modelo;
    private javax.swing.JTextField fld_numeroSerie;
    private javax.swing.JTextField fld_tipoEquipo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_ModificadoPor;
    private javax.swing.JLabel lbl_estatus1;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_icono;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_modelo2;
    private javax.swing.JLabel lbl_modelo3;
    private javax.swing.JLabel lbl_numeroSerie1;
    private javax.swing.JLabel lbl_reporteCapturista;
    private javax.swing.JLabel lbl_reporteTecnico;
    private javax.swing.JLabel lbl_tipoEquipo;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JLabel lbl_title2;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JTextPane txt_reporteCapturista;
    private javax.swing.JTextPane txt_reporteTecnico;
    // End of variables declaration//GEN-END:variables
}
