/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esrg.ventana;

import clases.Conexion;
import java.awt.Color;
import java.sql.*;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ESRG
 */
public class InformacionUsuario extends javax.swing.JFrame {
    
    public static int ID = 0;

    /**
     * Creates new form InformacionUsuario
     */
    public InformacionUsuario() {
        initComponents();
        
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Data System | Información del usuario");
        lbl_footer.setText(Login.footer);
        
        ImageIcon image_wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon wallpaper = new ImageIcon(image_wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(wallpaper);
        
        ImageIcon image_icon = new ImageIcon("src/images/informationuser.png");
        Icon icono = new ImageIcon(image_icon.getImage().getScaledInstance(lbl_icon.getWidth(), lbl_icon.getHeight(), Image.SCALE_DEFAULT));
        lbl_icon.setIcon(icono);
        
        this.repaint();
        
        lbl_userEdit.setText(GestionarUsuario.table_update);
        lbl_modifyBy.setText("Modificado por " + Login.username);
        
        try {
            Connection cn = Conexion.conexion();
            PreparedStatement ps;
            ps = cn.prepareStatement("select * from usuarios where username = '" + GestionarUsuario.table_update + "'");
            
            ResultSet rs = ps.executeQuery();                        
            
            if(rs.next()){
                
                ID = rs.getInt("id_usuario");
                
                lbl_registerBy.setText("Registrado por " + rs.getString("registrado_por"));
                fld_name.setText(rs.getString("nombre_usuario"));
                fld_email.setText(rs.getString("email"));
                fld_phone.setText(rs.getString("telefono"));
                fld_username.setText(rs.getString("username"));
                cmb_estatus.setSelectedItem(rs.getString("estatus"));
                cmb_typeUser.setSelectedItem(rs.getString("tipo_nivel"));
                
            }
            cn.close();
            
        }catch(SQLException er){
            JOptionPane.showMessageDialog(null, "Error de conexión.");
            System.err.println("Error " + er);
        }
        
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();
        lbl_userEdit = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        fld_name = new javax.swing.JTextField();
        fld_email = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        fld_phone = new javax.swing.JTextField();
        lbl_typeUser = new javax.swing.JLabel();
        cmb_typeUser = new javax.swing.JComboBox<>();
        lbl_username = new javax.swing.JLabel();
        fld_username = new javax.swing.JTextField();
        bttn_resetpassword = new javax.swing.JButton();
        lbl_footer = new javax.swing.JLabel();
        lbl_estatus = new javax.swing.JLabel();
        cmb_estatus = new javax.swing.JComboBox<>();
        bttn_modify = new javax.swing.JButton();
        lbl_modifyBy = new javax.swing.JLabel();
        lbl_registerBy = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Información de usuario");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
        getContentPane().add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 80));

        lbl_userEdit.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_userEdit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userEdit.setText("Nombre de usuario");
        getContentPane().add(lbl_userEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        lbl_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_name.setText("Nombre");
        getContentPane().add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 180, -1));

        fld_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 180, 20));

        fld_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, 20));

        lbl_email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_email.setText("Correo electrónico");
        getContentPane().add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 180, -1));

        lbl_phone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_phone.setForeground(new java.awt.Color(255, 255, 255));
        lbl_phone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_phone.setText("Teléfono");
        getContentPane().add(lbl_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 120, -1));

        fld_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_phone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 180, 20));

        lbl_typeUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_typeUser.setForeground(new java.awt.Color(255, 255, 255));
        lbl_typeUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_typeUser.setText("Tipo de usuario");
        getContentPane().add(lbl_typeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 180, -1));

        cmb_typeUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmb_typeUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Técnico" }));
        cmb_typeUser.setBorder(null);
        getContentPane().add(cmb_typeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 180, -1));

        lbl_username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_username.setText("Username");
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 180, -1));

        fld_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_username.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 180, 20));

        bttn_resetpassword.setBackground(new java.awt.Color(63, 84, 147));
        bttn_resetpassword.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bttn_resetpassword.setForeground(new java.awt.Color(255, 255, 255));
        bttn_resetpassword.setText("Restaurar contraseña");
        bttn_resetpassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttn_resetpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_resetpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_resetpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 390, 30));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 580, -1));

        lbl_estatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_estatus.setForeground(new java.awt.Color(255, 255, 255));
        lbl_estatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_estatus.setText("Estatus");
        getContentPane().add(lbl_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 180, -1));

        cmb_estatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cmb_estatus.setBorder(null);
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 180, -1));

        bttn_modify.setBackground(new java.awt.Color(63, 84, 147));
        bttn_modify.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bttn_modify.setForeground(new java.awt.Color(255, 255, 255));
        bttn_modify.setText("Guardar cambios");
        bttn_modify.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttn_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_modifyActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 390, 30));

        lbl_modifyBy.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lbl_modifyBy.setForeground(new java.awt.Color(63, 84, 147));
        lbl_modifyBy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_modifyBy.setText("Modificado por");
        getContentPane().add(lbl_modifyBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 180, -1));

        lbl_registerBy.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lbl_registerBy.setForeground(new java.awt.Color(255, 255, 255));
        lbl_registerBy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_registerBy.setText("Registrado por");
        getContentPane().add(lbl_registerBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 180, -1));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_resetpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_resetpasswordActionPerformed
        RestaurarPassword window = new RestaurarPassword();
        window.setVisible(true);
    }//GEN-LAST:event_bttn_resetpasswordActionPerformed

    private void bttn_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_modifyActionPerformed
        int tipo_usuario = cmb_typeUser.getSelectedIndex() + 1;
        int contador_errorVacio = 0;
                
        if(fld_name.getText().trim().equals("")){
            fld_name.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            contador_errorVacio++;
        } else {
            fld_name.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }
        
        
        boolean flagEmail = false, executeInavalid = false; 
        if (fld_email.getText().trim().equals("")) {

            fld_email.setBorder(BorderFactory.createLineBorder(new Color(180, 0, 0), 1));
            contador_errorVacio++;
            
        } else {
            
            if(fld_email.getText().trim().length() > 12){
                
                if (fld_email.getText().trim().substring((fld_email.getText().length() - 4),
                        fld_email.getText().length()).equals(".com")) {
                    
                    boolean flagArroba = false;
                    for (int i = 0; i < fld_email.getText().trim().length(); i++) {
                        
                        if(fld_email.getText().trim().substring(i,(i+1)).equals("@")){
                            flagArroba = true;
                            i = 120;
                        }
                    }
                    if(flagArroba == true){
                        fld_email.setBorder(BorderFactory.createLineBorder(new Color(0, 180, 0), 1));
                        flagEmail = true;
                    } else {
                         fld_email.setBorder(BorderFactory.createLineBorder(new Color(180, 0, 0), 1));            
                         
                         executeInavalid = true;
                    }
                    
                } else {
                    fld_email.setBorder(BorderFactory.createLineBorder(new Color(180, 0, 0), 1));            
                    
                    executeInavalid = true;
                }
                
            } else {
                fld_email.setBorder(BorderFactory.createLineBorder(new Color(180, 0, 0), 1));
                
                executeInavalid = true;
            }
            
        }
        
        
        if(fld_phone.getText().trim().equals("")){
            fld_phone.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            contador_errorVacio++;
        } else {
            fld_phone.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }
        
        if (fld_username.getText().trim().equals("")) {
            fld_username.setBorder(BorderFactory.createLineBorder(new Color(180, 0, 0), 1));
            contador_errorVacio++;
        } else {
            fld_username.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }
        
        if (fld_username.getText().trim().equals("")) {
            fld_username.setBorder(BorderFactory.createLineBorder(new Color(180, 0, 0), 1));
            contador_errorVacio++;
        } else {
            fld_username.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }                          
        
        
        if (contador_errorVacio > 0 || executeInavalid == true) {
            
            if(contador_errorVacio > 0 && executeInavalid == false){
               JOptionPane.showMessageDialog(null, "Ingrese los datos solicitados."); 
            } else if(executeInavalid == true && contador_errorVacio == 0){
               JOptionPane.showMessageDialog(null, "Correo electrónico no válido.");  
            } else if(executeInavalid == true && contador_errorVacio > 0){
               JOptionPane.showMessageDialog(null, "Ingrese los datos solicitados."); 
               JOptionPane.showMessageDialog(null, "Correo electrónico no válido.");  
            }

        } else {
            
            try {
                Connection cn = Conexion.conexion();
                PreparedStatement ps;
                ps = cn.prepareStatement("select username from usuarios where username = '"
                        + fld_username.getText().trim() + "'");
                
                ResultSet result = ps.executeQuery();
                boolean luzverde = false;
                if (result.next()) {    
                    
                    if(result.getString("username").equalsIgnoreCase(GestionarUsuario.table_update)){                        
                        fld_username.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
                        luzverde = true;
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "Nombre de usuario en uso.");
                        fld_username.setBorder(BorderFactory.createLineBorder(new Color(180, 0, 0), 1));    
                    }    
                    
                } else {                    
                    fld_username.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
                    luzverde = true;
                }
                cn.close();
                
                if(luzverde == true){
                    
                    try {
                        Connection cn1 = Conexion.conexion();
                        PreparedStatement ps1 = cn1.prepareStatement("update usuarios set nombre_usuario = ?, email = ?, telefono = ?, "
                                + "username = ?, tipo_nivel = ?, estatus = ? where id_usuario = '" + ID + "'");
                        
                        ps1.setString(1, fld_name.getText().trim());
                        ps1.setString(2, fld_email.getText().trim());
                        ps1.setString(3, fld_phone.getText().trim());
                        ps1.setString(4, fld_username.getText().trim());
                        ps1.setString(5, cmb_typeUser.getSelectedItem().toString().trim());
                        ps1.setString(6, cmb_estatus.getSelectedItem().toString().trim());
                        
                        ps1.executeUpdate();
                        
                        JOptionPane.showMessageDialog(null, "Datos actualizados correctamente.");
                        
                        cn1.close();
                        
                        this.dispose();                        
                        
                    } catch (SQLException e) {                        
                        System.err.println("Error " + e);
                    }
                    
                }
                
                
            } catch (SQLException e) {
               System.err.println("Error " + e);
            }
                
        }
    }//GEN-LAST:event_bttn_modifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_modify;
    private javax.swing.JButton bttn_resetpassword;
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JComboBox<String> cmb_typeUser;
    private javax.swing.JTextField fld_email;
    private javax.swing.JTextField fld_name;
    private javax.swing.JTextField fld_phone;
    private javax.swing.JTextField fld_username;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_estatus;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_modifyBy;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_registerBy;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_typeUser;
    private javax.swing.JLabel lbl_userEdit;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_wallpaper;
    // End of variables declaration//GEN-END:variables
}
