/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esrg.ventana;

import java.sql.*;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
import javax.swing.BorderFactory;

/**
 *
 * @author ESRG
 */
public class InformacionEquipo extends javax.swing.JFrame {

    /**
     * Creates new form InformacionEquipo
     */
    public InformacionEquipo() {
        initComponents();
        
        setTitle("Data System | Información de equipo");
        setResizable(false);
        setLocationRelativeTo(null);
        lbl_footer.setText(Login.footer);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon image_icon = new ImageIcon("src/images/apoyo-tecnico.png");
        Icon icono = new ImageIcon(image_icon.getImage().getScaledInstance(lbl_icono.getWidth(), lbl_icono.getHeight(), Image.SCALE_DEFAULT));
        lbl_icono.setIcon(icono);  
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon iconoWallpaper = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(iconoWallpaper);
        
        lbl_title2.setText("ID del equipo: " + InformacionCliente.table_update);
        fld_name.setText(InformacionCliente.nombre_cliente);
        fld_fecha.setCaretColor(Color.white);
        txt_reporteTecnico.setEditable(false);
        txt_reporteTecnico.setCaretColor(Color.white);
        
        try {
            Connection cn = clases.Conexion.conexion();
            PreparedStatement ps = cn.prepareStatement("select * from equipos where id_equipo = '" + InformacionCliente.table_update + "'");
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                lbl_ModificadoPor.setText("Modificado por: " + rs.getString("ultima_modificacion"));
                fld_fecha.setText(rs.getString("dia_ingreso") + "/" + rs.getString("mes_ingreso") + "/" + rs.getString("annio_ingreso"));
                fld_numeroSerie.setText(rs.getString("num_serie"));       
                fld_modelo.setText(rs.getString("modelo"));
                cmb_tipoEquipo.setSelectedItem(rs.getString("tipo_equipo"));  
                cmb_marca.setSelectedItem(rs.getString("marca")); 
                cmb_estatus.setSelectedItem(rs.getString("estatus")); 
                txt_reporteCapturista.setText(rs.getString("observaciones"));
                txt_reporteTecnico.setText(rs.getString("comentarios_tecnicos"));
                lbl_reporteTecnico.setText("Reporte del técnico: " + rs.getString("revision_tecnica_de"));
            }
            
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error: " + e);
        }
        
        if(cmb_estatus.getSelectedItem().equals("Entregado") && !Login.tipoNivel.equals("Administrador")){
            bttn_actualizarEquipo.setEnabled(false);
        }
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();
        lbl_userEdit = new javax.swing.JLabel();
        lbl_title1 = new javax.swing.JLabel();
        lbl_icono = new javax.swing.JLabel();
        lbl_title2 = new javax.swing.JLabel();
        lbl_reporteTecnico = new javax.swing.JLabel();
        lbl_tipoEquipo = new javax.swing.JLabel();
        lbl_marca = new javax.swing.JLabel();
        lbl_modelo = new javax.swing.JLabel();
        lbl_numeroSerie = new javax.swing.JLabel();
        fld_name = new javax.swing.JTextField();
        fld_modelo = new javax.swing.JTextField();
        fld_numeroSerie = new javax.swing.JTextField();
        cmb_tipoEquipo = new javax.swing.JComboBox<>();
        cmb_marca = new javax.swing.JComboBox<>();
        lbl_ModificadoPor = new javax.swing.JLabel();
        lbl_modelo1 = new javax.swing.JLabel();
        fld_fecha = new javax.swing.JTextField();
        lbl_estatus = new javax.swing.JLabel();
        cmb_estatus = new javax.swing.JComboBox<>();
        lbl_footer = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_reporteTecnico = new javax.swing.JTextPane();
        lbl_name1 = new javax.swing.JLabel();
        lbl_reporteCapturista = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_reporteCapturista = new javax.swing.JTextPane();
        bttn_actualizarEquipo = new javax.swing.JButton();
        lbl_wallpaper = new javax.swing.JLabel();

        lbl_title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Información de usuario");

        lbl_userEdit.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_userEdit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userEdit.setText("Nombre de usuario");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title1.setText("Información de equipo");
        getContentPane().add(lbl_title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
        getContentPane().add(lbl_icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 80));

        lbl_title2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_title2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title2.setText("ID del equipo: ");
        getContentPane().add(lbl_title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        lbl_reporteTecnico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_reporteTecnico.setForeground(new java.awt.Color(255, 255, 255));
        lbl_reporteTecnico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_reporteTecnico.setText("Comentarios y actualización del técnico");
        getContentPane().add(lbl_reporteTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 390, -1));

        lbl_tipoEquipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_tipoEquipo.setForeground(new java.awt.Color(102, 102, 255));
        lbl_tipoEquipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_tipoEquipo.setText("Tipo de equipo");
        getContentPane().add(lbl_tipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 180, -1));

        lbl_marca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_marca.setForeground(new java.awt.Color(102, 102, 255));
        lbl_marca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_marca.setText("Marca");
        getContentPane().add(lbl_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 180, -1));

        lbl_modelo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_modelo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_modelo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_modelo.setText("Modelo");
        getContentPane().add(lbl_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 180, -1));

        lbl_numeroSerie.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_numeroSerie.setForeground(new java.awt.Color(255, 255, 255));
        lbl_numeroSerie.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_numeroSerie.setText("Número de serie");
        getContentPane().add(lbl_numeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 180, -1));

        fld_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, 20));

        fld_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_modelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 180, 20));

        fld_numeroSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_numeroSerie.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_numeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 180, 20));

        cmb_tipoEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Impresora", "Multifuncional" }));
        getContentPane().add(cmb_tipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 180, -1));

        cmb_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "Alienware", "Apple", "Asus", "Brother", "Dell", "HP", "Lenovo", "Samsung", "Toshiba", "Xerox" }));
        getContentPane().add(cmb_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 180, -1));

        lbl_ModificadoPor.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lbl_ModificadoPor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ModificadoPor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_ModificadoPor.setText("Modificado por:");
        getContentPane().add(lbl_ModificadoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 390, -1));

        lbl_modelo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_modelo1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_modelo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_modelo1.setText("Fecha de ingreso");
        getContentPane().add(lbl_modelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 180, -1));

        fld_fecha.setEditable(false);
        fld_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_fecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 180, 20));

        lbl_estatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_estatus.setForeground(new java.awt.Color(102, 102, 255));
        lbl_estatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_estatus.setText("Estatus");
        getContentPane().add(lbl_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 180, -1));

        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo ingreso", "No reparado", "En revisión", "Reparado", "Entregado" }));
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 180, -1));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 780, -1));

        jScrollPane2.setEnabled(false);

        txt_reporteTecnico.setEditable(false);
        jScrollPane2.setViewportView(txt_reporteTecnico);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 390, 120));

        lbl_name1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_name1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_name1.setText("Nombre del cliente");
        getContentPane().add(lbl_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 180, -1));

        lbl_reporteCapturista.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_reporteCapturista.setForeground(new java.awt.Color(255, 255, 255));
        lbl_reporteCapturista.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_reporteCapturista.setText("Daño reportado y observaciones");
        getContentPane().add(lbl_reporteCapturista, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 240, -1));

        jScrollPane3.setViewportView(txt_reporteCapturista);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 390, 120));

        bttn_actualizarEquipo.setBackground(new java.awt.Color(63, 84, 147));
        bttn_actualizarEquipo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bttn_actualizarEquipo.setForeground(new java.awt.Color(255, 255, 255));
        bttn_actualizarEquipo.setText("Actualizar equipo");
        bttn_actualizarEquipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttn_actualizarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_actualizarEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_actualizarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 390, 30));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_actualizarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_actualizarEquipoActionPerformed
        
        int errores = 0;
        
        if(fld_name.getText().equals("")){
            fld_name.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            errores++;
        } else {
            fld_name.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }
        
        if(fld_numeroSerie.getText().equals("")){
            fld_numeroSerie.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            errores++;
        } else {
            fld_numeroSerie.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }
        
        if(fld_modelo.getText().equals("")){
            fld_modelo.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            errores++;
        } else {
            fld_modelo.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }
        
        if(txt_reporteCapturista.getText().equals("")){
            txt_reporteCapturista.setText("Sin observaciones.");
        }
        
        if(errores != 0){
            javax.swing.JOptionPane.showMessageDialog(null, "Ingrese los datos solicitados");
        } else {
            
            try {
                Connection cn = clases.Conexion.conexion();
                PreparedStatement ps = cn.prepareStatement("update equipos set num_serie = ?, modelo = ?, tipo_equipo = ?, marca = ?, estatus = ?,"
                        + " observaciones = ?, ultima_modificacion = ? where id_equipo = '" + InformacionCliente.table_update + "'");
                
                ps.setString(1, fld_numeroSerie.getText().trim());
                ps.setString(2, fld_modelo.getText().trim());
                ps.setString(3, cmb_tipoEquipo.getSelectedItem().toString());
                ps.setString(4, cmb_marca.getSelectedItem().toString());
                ps.setString(5, cmb_estatus.getSelectedItem().toString());
                ps.setString(6, txt_reporteCapturista.getText().trim());
                ps.setString(7, Login.username);
                
                ps.executeUpdate();
                cn.close();
                
                javax.swing.JOptionPane.showMessageDialog(null, "Equipo actualizado correctamente.");
                
                dispose();
                
            } catch (SQLException e) {
                System.out.println("Error " + e);
            }
        }
    }//GEN-LAST:event_bttn_actualizarEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_actualizarEquipo;
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JComboBox<String> cmb_marca;
    private javax.swing.JComboBox<String> cmb_tipoEquipo;
    private javax.swing.JTextField fld_fecha;
    private javax.swing.JTextField fld_modelo;
    private javax.swing.JTextField fld_name;
    private javax.swing.JTextField fld_numeroSerie;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_ModificadoPor;
    private javax.swing.JLabel lbl_estatus;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_icono;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_modelo1;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_numeroSerie;
    private javax.swing.JLabel lbl_reporteCapturista;
    private javax.swing.JLabel lbl_reporteTecnico;
    private javax.swing.JLabel lbl_tipoEquipo;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JLabel lbl_title2;
    private javax.swing.JLabel lbl_userEdit;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JTextPane txt_reporteCapturista;
    private javax.swing.JTextPane txt_reporteTecnico;
    // End of variables declaration//GEN-END:variables
}
