package esrg.ventana;

/**
 *
 * @author ESRG
 */
import javax.swing.ImageIcon;
import javax.swing.Icon;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

import java.sql.*;

import clases.Conexion;

public class Login extends javax.swing.JFrame {
    
    public static String nombreUsuario, username, tipoNivel;
    public static final String footer = "Created by: La Geekipedia de Ernesto. Developed by: ESRG";
    

    /**
     * Creates new form Login
     */
    public Login() {
        
        System.out.println("¡Alabado sea DIOS, creador de los cielos y de la tierra, y de todas las ciencias!");
        
        initComponents();
        
        setTitle("Data System | Acceso al sistema");
        setResizable(false);
        setLocationRelativeTo(null);       
        setDefaultCloseOperation(EXIT_ON_CLOSE);  
        lbl_footer.setText(footer);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(), 
                Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icono);
        
        
        ImageIcon logo = new ImageIcon("src/images/DS.png");
        Icon icono_logo = new ImageIcon(logo.getImage().getScaledInstance(lbl_logo.getWidth(), lbl_logo.getHeight(), 
                Image.SCALE_DEFAULT));
        lbl_logo.setIcon(icono_logo);
        
        
        this.repaint();      
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_logo = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        fld_user = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        fld_password = new javax.swing.JPasswordField();
        chk_password = new javax.swing.JCheckBox();
        bttn_input = new javax.swing.JButton();
        lbl_footer = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 270));

        lbl_title.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Iniciar sesión");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        lbl_user.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(255, 255, 255));
        lbl_user.setText("Nombre de usuario");
        getContentPane().add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        fld_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_user.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 180, 20));

        lbl_password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(255, 255, 255));
        lbl_password.setText("Contraseña");
        getContentPane().add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        fld_password.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        fld_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fld_password.setEchoChar('\u25cf');
        getContentPane().add(fld_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 180, 20));

        chk_password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_password.setForeground(new java.awt.Color(255, 255, 255));
        chk_password.setText("Mostrar contraseña");
        chk_password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        chk_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(chk_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        bttn_input.setBackground(new java.awt.Color(63, 84, 147));
        bttn_input.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bttn_input.setForeground(new java.awt.Color(255, 255, 255));
        bttn_input.setText("Entrar");
        bttn_input.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_inputActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 180, 30));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 320, 610, -1));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_passwordActionPerformed
        if(chk_password.isSelected() == true){
            fld_password.setEchoChar((char) 0);
        } else {
            fld_password.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_chk_passwordActionPerformed

    private void bttn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_inputActionPerformed
        
        //Conexion conexion = new Conexion();
        
        if(fld_user.getText().equals("") || fld_password.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese los datos solicitados.");
        } else {
            try {               
                
                Connection conexion = Conexion.conexion();                        
                PreparedStatement ps_user = conexion.prepareStatement("select * from usuarios where username = ? ");    
                
                ps_user.setString(1, fld_user.getText().trim());
                
                ResultSet rs = ps_user.executeQuery();                                                               
                
                if(rs.next()){   
                    
                    nombreUsuario = rs.getString("nombre_usuario");
                    username = rs.getString("username");
                    tipoNivel = rs.getString("tipo_nivel");
                    
                    if(fld_password.getText().equals(rs.getString("password"))){
                        
                        if(rs.getString("tipo_nivel").equalsIgnoreCase("Administrador") 
                                && rs.getString("estatus").equalsIgnoreCase("Activo")){
                            
                            dispose();
                            new Administrador().setVisible(true);
                            //JOptionPane.showMessageDialog(null, "Hola " + nombreUsuario);
                            
                        } else if(rs.getString("tipo_nivel").equalsIgnoreCase("Capturista") 
                                && rs.getString("estatus").equalsIgnoreCase("Activo")){
                            
                            dispose();
                            new Capturista().setVisible(true);
                             
                        } else if(rs.getString("tipo_nivel").equalsIgnoreCase("Técnico") 
                                && rs.getString("estatus").equalsIgnoreCase("Activo")){
                            
                            dispose();
                            new Tecnico().setVisible(true);
                            
                        } else {
                            fld_user.setText("");
                            fld_password.setText("");
                            JOptionPane.showMessageDialog(null, "Usuario inactivo.");
                        }
                        
                    } else {
                        fld_password.setText("");
                        JOptionPane.showMessageDialog(null, "Contraseña incorrecta.");
                    }
                    
                } else {
                    fld_user.setText("");
                    fld_password.setText("");
                    JOptionPane.showMessageDialog(null, "Usuario no existente.");
                }
                
                conexion.close();
                
            } catch (Exception e) {
                System.err.println("Error " + e);               
            }
        }
    }//GEN-LAST:event_bttn_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_input;
    private javax.swing.JCheckBox chk_password;
    private javax.swing.JPasswordField fld_password;
    private javax.swing.JTextField fld_user;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_wallpaper;
    // End of variables declaration//GEN-END:variables
}
