/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esrg.ventana;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import java.sql.*;

/**
 *
 * @author ESRG
 */
public class RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form AgregarUsuario
     */
    public RegistroUsuario() {
        initComponents();
        
        setTitle("Data System | Agregar usuario");
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        lbl_footer.setText(Login.footer);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon wallpaper_icon = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(wallpaper_icon);
        
        this.repaint();
        
        ImageIcon addUser = new ImageIcon("src/images/add.png");
        Icon add_user_icon = new ImageIcon(addUser.getImage().getScaledInstance(lbl_icon.getWidth(), lbl_icon.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_icon.setIcon(add_user_icon);
        
        /**
        ImageIcon logo = new ImageIcon("src/images/DS.png");
        Icon icono_logo = new ImageIcon(logo.getImage().getScaledInstance(lbl_logo.getWidth(), lbl_logo.getHeight(), 
                Image.SCALE_DEFAULT));
        lbl_logo.setIcon(icono_logo);
        * */
        
        lbl_registradoPor.setText("Registrado por " + Login.username);
        
        this.repaint();
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        fld_name = new javax.swing.JTextField();
        fld_email = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        fld_phone = new javax.swing.JTextField();
        lbl_typeUser = new javax.swing.JLabel();
        cbx_typeUser = new javax.swing.JComboBox<>();
        lbl_username = new javax.swing.JLabel();
        fld_username = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        fld_password = new javax.swing.JPasswordField();
        chk_password = new javax.swing.JCheckBox();
        bttn_registro = new javax.swing.JButton();
        lbl_footer = new javax.swing.JLabel();
        lbl_registradoPor = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Registro de usuario");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
        getContentPane().add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 80));

        lbl_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_name.setText("Nombre");
        getContentPane().add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 180, -1));

        fld_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 180, 20));

        fld_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, 20));

        lbl_email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_email.setText("Correo electrónico");
        getContentPane().add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 180, -1));

        lbl_phone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_phone.setForeground(new java.awt.Color(255, 255, 255));
        lbl_phone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_phone.setText("Télefono");
        getContentPane().add(lbl_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 120, -1));

        fld_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_phone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 180, 20));

        lbl_typeUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_typeUser.setForeground(new java.awt.Color(255, 255, 255));
        lbl_typeUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_typeUser.setText("Tipo de usuario");
        getContentPane().add(lbl_typeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 180, -1));

        cbx_typeUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbx_typeUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Técnico" }));
        cbx_typeUser.setBorder(null);
        getContentPane().add(cbx_typeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 180, -1));

        lbl_username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_username.setText("Username");
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 180, -1));

        fld_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_username.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 180, 20));

        lbl_password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(255, 255, 255));
        lbl_password.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_password.setText("Contraseña");
        getContentPane().add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 180, -1));

        fld_password.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        fld_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fld_password.setEchoChar('\u25cf');
        getContentPane().add(fld_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 180, 20));

        chk_password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_password.setForeground(new java.awt.Color(63, 84, 147));
        chk_password.setText("Mostrar contraseña");
        chk_password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        chk_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(chk_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        bttn_registro.setBackground(new java.awt.Color(63, 84, 147));
        bttn_registro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bttn_registro.setForeground(new java.awt.Color(255, 255, 255));
        bttn_registro.setText("Registrar");
        bttn_registro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_registroActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 390, 30));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 400, 590, -1));

        lbl_registradoPor.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_registradoPor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_registradoPor.setText("Registrado");
        getContentPane().add(lbl_registradoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_passwordActionPerformed
        if(chk_password.isSelected() == true){
            fld_password.setEchoChar((char) 0);
        } else {
            fld_password.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_chk_passwordActionPerformed

    private void bttn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_registroActionPerformed
        
        int tipo_usuario = cbx_typeUser.getSelectedIndex() + 1;
        int contador_errorVacio = 0;
                
        if(fld_name.getText().trim().equals("")){
            fld_name.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            contador_errorVacio++;
        } else {
            fld_name.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }
        
        
        boolean flagEmail = false, executeInavalid = false; 
        if (fld_email.getText().trim().equals("")) {

            fld_email.setBorder(BorderFactory.createLineBorder(new Color(180, 0, 0), 1));
            contador_errorVacio++;
            
        } else {
            
            if(fld_email.getText().trim().length() > 12){
                
                if (fld_email.getText().trim().substring((fld_email.getText().length() - 4),
                        fld_email.getText().length()).equals(".com")) {
                    
                    boolean flagArroba = false;
                    for (int i = 0; i < fld_email.getText().trim().length(); i++) {
                        
                        if(fld_email.getText().trim().substring(i,(i+1)).equals("@")){
                            flagArroba = true;
                            i = 120;
                        }
                    }
                    if(flagArroba == true){
                        fld_email.setBorder(BorderFactory.createLineBorder(new Color(0, 180, 0), 1));
                        flagEmail = true;
                    } else {
                         fld_email.setBorder(BorderFactory.createLineBorder(new Color(180, 0, 0), 1));            
                         
                         executeInavalid = true;
                    }
                    
                } else {
                    fld_email.setBorder(BorderFactory.createLineBorder(new Color(180, 0, 0), 1));            
                    
                    executeInavalid = true;
                }
                
            } else {
                fld_email.setBorder(BorderFactory.createLineBorder(new Color(180, 0, 0), 1));
                
                executeInavalid = true;
            }
            
        }
        
        
        if(fld_phone.getText().trim().equals("")){
            fld_phone.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            contador_errorVacio++;
        } else {
            fld_phone.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }
        if(tipo_usuario == 1){
            
        } else if(tipo_usuario == 2){
            
        } else if(tipo_usuario == 3){
            
        }
        if (fld_username.getText().trim().equals("")) {
            fld_username.setBorder(BorderFactory.createLineBorder(new Color(180, 0, 0), 1));
            contador_errorVacio++;
        } else {
            fld_username.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }
        
        if(fld_password.getText().trim().equals("")){
            fld_password.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            contador_errorVacio++;
        } else {
            fld_password.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }           
        
        
        if (contador_errorVacio > 0 || executeInavalid == true) {
            
            if(contador_errorVacio > 0 && executeInavalid == false){
               JOptionPane.showMessageDialog(null, "Ingrese los datos solicitados."); 
            } else if(executeInavalid == true && contador_errorVacio == 0){
               JOptionPane.showMessageDialog(null, "Correo electrónico no válido.");  
            } else if(executeInavalid == true && contador_errorVacio > 0){
               JOptionPane.showMessageDialog(null, "Ingrese los datos solicitados."); 
               JOptionPane.showMessageDialog(null, "Correo electrónico no válido.");  
            }

        } else {
            try {
                Connection conexion = Conexion.conexion();
                PreparedStatement ps = conexion.prepareStatement("select username from usuarios where username = '"
                        + fld_username.getText().trim() + "'");
                ResultSet result = ps.executeQuery();
                if (result.next()) {
                    JOptionPane.showMessageDialog(null, "Nombre de usuario en uso.");
                    fld_username.setBorder(BorderFactory.createLineBorder(new Color(180, 0, 0), 1));
                } else {
                     
                    PreparedStatement ps1 = conexion.prepareStatement("insert into usuarios values(?,?,?,?,?,?,?,?,?)");
                    
                    ps1.setString(1, "0");
                    ps1.setString(2, fld_name.getText().trim());
                    ps1.setString(3, fld_email.getText().trim());
                    ps1.setString(4, fld_phone.getText().trim());
                    ps1.setString(5, fld_username.getText().trim());
                    ps1.setString(6, fld_password.getText().trim());
                    ps1.setString(7, cbx_typeUser.getSelectedItem().toString());
                    ps1.setString(8, "Activo");
                    ps1.setString(9, Login.username);
                    
                    ps1.executeUpdate();
                                                            
                    JOptionPane.showMessageDialog(null, "Usuario registrado correctamente");
                    
                    dispose();
                    
                }
                conexion.close();
                
            } catch (SQLException e) {
                System.err.println("Error " + e);
            }
                        
            
        }
        
        
        
        
        
    }//GEN-LAST:event_bttn_registroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_registro;
    private javax.swing.JComboBox<String> cbx_typeUser;
    private javax.swing.JCheckBox chk_password;
    private javax.swing.JTextField fld_email;
    private javax.swing.JTextField fld_name;
    private javax.swing.JPasswordField fld_password;
    private javax.swing.JTextField fld_phone;
    private javax.swing.JTextField fld_username;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_registradoPor;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_typeUser;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_wallpaper;
    // End of variables declaration//GEN-END:variables
}
