/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esrg.ventana;

import java.sql.*;
import clases.Conexion;

import java.util.Calendar;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
import javax.swing.BorderFactory;

/**
 *
 * @author RG
 */
public class RegistroEquipo extends javax.swing.JFrame {
    
    int id_cliente;
    Calendar calendario = Calendar.getInstance();

    /**
     * Creates new form RegistroEquipo
     */
    public RegistroEquipo() {
        initComponents();
        
        setTitle("Data System | Registrar equipo");
        setResizable(false);
        setLocationRelativeTo(null);
        lbl_footer.setText(Login.footer);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon img_wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon_wallpaper = new ImageIcon(img_wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icon_wallpaper);
        
        ImageIcon image_icon = new ImageIcon("src/images/apoyo-tecnico.png");
        Icon icono = new ImageIcon(image_icon.getImage().getScaledInstance(lbl_icon.getWidth(), lbl_icon.getHeight(), Image.SCALE_DEFAULT));
        lbl_icon.setIcon(icono);
        
        this.repaint();
        
        cmb_marca.setMaximumRowCount(9);
        
        try {
            Connection cn = Conexion.conexion();
            PreparedStatement pst = cn.prepareStatement(
                    "select id_Cliente, nombre_cliente from clientes where id_cliente = '" + GestionarCliente.table_update + "'");
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                id_cliente= rs.getInt("id_cliente");
                lbl_subTitle.setText(rs.getString("nombre_cliente"));
                fld_name.setText(rs.getString("nombre_cliente"));
            }
        } catch (SQLException e) {
            System.err.println("Error: " + e);
        }
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();
        lbl_subTitle = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_tipoEquipo = new javax.swing.JLabel();
        lbl_marca = new javax.swing.JLabel();
        lbl_modelo = new javax.swing.JLabel();
        lbl_numeroSerie = new javax.swing.JLabel();
        lbl_observaciones = new javax.swing.JLabel();
        fld_name = new javax.swing.JTextField();
        fld_modelo = new javax.swing.JTextField();
        fld_numeroSerie = new javax.swing.JTextField();
        cmb_tipoEquipo = new javax.swing.JComboBox<>();
        cmb_marca = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextPane();
        bttn_actualizarUsuario = new javax.swing.JButton();
        lbl_footer = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Registrar equipo");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
        getContentPane().add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 80));

        lbl_subTitle.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_subTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_subTitle.setText("Nombre de usuario");
        getContentPane().add(lbl_subTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        lbl_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_name.setText("Nombre del cliente");
        getContentPane().add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 180, -1));

        lbl_tipoEquipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_tipoEquipo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipoEquipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_tipoEquipo.setText("Tipo de equipo");
        getContentPane().add(lbl_tipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 180, -1));

        lbl_marca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_marca.setForeground(new java.awt.Color(255, 255, 255));
        lbl_marca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_marca.setText("Marca");
        getContentPane().add(lbl_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 180, -1));

        lbl_modelo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_modelo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_modelo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_modelo.setText("Modelo");
        getContentPane().add(lbl_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 180, -1));

        lbl_numeroSerie.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_numeroSerie.setForeground(new java.awt.Color(255, 255, 255));
        lbl_numeroSerie.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_numeroSerie.setText("Número de serie");
        getContentPane().add(lbl_numeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 180, -1));

        lbl_observaciones.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_observaciones.setForeground(new java.awt.Color(255, 255, 255));
        lbl_observaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_observaciones.setText("Daño reportado y observaciones");
        getContentPane().add(lbl_observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 260, -1));

        fld_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, 20));

        fld_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_modelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 180, 20));

        fld_numeroSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_numeroSerie.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_numeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 180, 20));

        cmb_tipoEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Impresora", "Multifuncional" }));
        getContentPane().add(cmb_tipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 180, -1));

        cmb_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "Alienware", "Apple", "Asus", "Brother", "Dell", "HP", "Lenovo", "Samsung", "Toshiba", "Xerox" }));
        getContentPane().add(cmb_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 180, -1));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(txt_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 390, 130));

        bttn_actualizarUsuario.setBackground(new java.awt.Color(63, 84, 147));
        bttn_actualizarUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bttn_actualizarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        bttn_actualizarUsuario.setText("Agregar equipo");
        bttn_actualizarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttn_actualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_actualizarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_actualizarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 390, 30));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 580, -1));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 581, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_actualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_actualizarUsuarioActionPerformed

        int contador_errorVacio = 0;
        
        if(fld_name.getText().equals("")){
            fld_name.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            contador_errorVacio++;
        } else {
            fld_name.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }
        
        if(fld_modelo.getText().equals("")){
            fld_modelo.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            contador_errorVacio++;
        } else {
            fld_modelo.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }
        
        if(fld_numeroSerie.getText().equals("")){
            fld_numeroSerie.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            contador_errorVacio++;
        } else {
            fld_numeroSerie.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }
        
        if(txt_observaciones.getText().equals("")){
            txt_observaciones.setBorder(BorderFactory.createLineBorder(new Color(180,180,180), 1));
            txt_observaciones.setText("Sin observaciones.");
        } else {
            txt_observaciones.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        }
        
        if (contador_errorVacio > 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Ingrese los datos solicitados");
        } else {
            try{
                Connection cn = Conexion.conexion();
                PreparedStatement ps = cn.prepareStatement("insert into `equipos` (id_cliente, tipo_equipo, marca, modelo, num_serie, dia_ingreso, mes_ingreso,"
                        + "annio_ingreso, observaciones, estatus, comentarios_tecnicos, ultima_modificacion, revision_tecnica_de) "
                        + "values(?,?,?,?,?,?,?,?,?,?,'',?,'')");
                
                ps.setInt(1, id_cliente);
                ps.setString(2, cmb_tipoEquipo.getSelectedItem().toString());
                ps.setString(3, cmb_marca.getSelectedItem().toString());
                ps.setString(4, fld_modelo.getText().trim());
                ps.setString(5, fld_numeroSerie.getText().trim());
                ps.setString(6, "" + (calendario.get(Calendar.DATE)));
                ps.setString(7, "" + (calendario.get(Calendar.MONTH) + 1));
                ps.setString(8, "" + (calendario.get(Calendar.YEAR)));
                ps.setString(9, txt_observaciones.getText());
                ps.setString(10, "Nuevo ingreso");
                ps.setString(11, Login.username);
                
                ps.executeUpdate();
                
                javax.swing.JOptionPane.showMessageDialog(null, "Se añadió un nuevo equipo.");                    
                dispose();
                
                cn.close();
                
            } catch(SQLException er){
                System.out.println("error: " + er);
            }
        }
    }//GEN-LAST:event_bttn_actualizarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_actualizarUsuario;
    private javax.swing.JComboBox<String> cmb_marca;
    private javax.swing.JComboBox<String> cmb_tipoEquipo;
    private javax.swing.JTextField fld_modelo;
    private javax.swing.JTextField fld_name;
    private javax.swing.JTextField fld_numeroSerie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_numeroSerie;
    private javax.swing.JLabel lbl_observaciones;
    private javax.swing.JLabel lbl_subTitle;
    private javax.swing.JLabel lbl_tipoEquipo;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JTextPane txt_observaciones;
    // End of variables declaration//GEN-END:variables
}
