/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esrg.ventana;

import clases.Conexion;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import java.sql.*;

/**
 *
 * @author ESRG
 */
public class RegistroCliente extends javax.swing.JFrame {

    /**
     * Creates new form RegistroCliente
     */
    public RegistroCliente() {
        initComponents();
        
        setTitle("Data System | Agregar cliente");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        lbl_footer.setText(Login.footer);
        
        ImageIcon icon_wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon wallpaper = new ImageIcon(icon_wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), 
                lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(wallpaper);
        
        ImageIcon icon = new ImageIcon("src/images/add.png");
        Icon logo = new ImageIcon(icon.getImage().getScaledInstance(lbl_icon.getWidth(), lbl_icon.getHeight(), 
                Image.SCALE_DEFAULT));
        lbl_icon.setIcon(logo);
        
        lbl_registradoPor.setText("Registrado por " + Login.username);
        
        this.repaint();
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();
        lbl_registradoPor = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        fld_name = new javax.swing.JTextField();
        fld_email = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        fld_phone = new javax.swing.JTextField();
        lbl_direc = new javax.swing.JLabel();
        fld_direc = new javax.swing.JTextField();
        bttn_registro = new javax.swing.JButton();
        lbl_footer = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Registro de cliente");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
        getContentPane().add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 80));

        lbl_registradoPor.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_registradoPor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_registradoPor.setText("Registrado");
        getContentPane().add(lbl_registradoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        lbl_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_name.setText("Nombre");
        getContentPane().add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 180, -1));

        fld_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 270, 20));

        fld_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 270, 20));

        lbl_email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_email.setText("Correo electrónico");
        getContentPane().add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 180, -1));

        lbl_phone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_phone.setForeground(new java.awt.Color(255, 255, 255));
        lbl_phone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_phone.setText("Télefono");
        getContentPane().add(lbl_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 120, -1));

        fld_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_phone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 270, 20));

        lbl_direc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_direc.setForeground(new java.awt.Color(255, 255, 255));
        lbl_direc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_direc.setText("Dirección");
        getContentPane().add(lbl_direc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 180, -1));

        fld_direc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_direc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fld_direc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 270, 20));

        bttn_registro.setBackground(new java.awt.Color(63, 84, 147));
        bttn_registro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bttn_registro.setForeground(new java.awt.Color(255, 255, 255));
        bttn_registro.setText("Añadir cliente");
        bttn_registro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_registroActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 270, 30));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 450, -1));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_registroActionPerformed
       
        int contador_errorVacio = 0;
        
        if(!fld_name.getText().equals("")){
           fld_name.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        } else {
            fld_name.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            contador_errorVacio++;
        }
        
        if(!fld_email.getText().equals("")){
            fld_email.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        } else {
            fld_email.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            contador_errorVacio++;
        }
        
        if(!fld_phone.getText().equals("")){
            fld_phone.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        } else {
            fld_phone.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            contador_errorVacio++;
        }
        
        if(!fld_direc.getText().equals("")){
            fld_direc.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
        } else {
            fld_direc.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
            contador_errorVacio++;
        }
        
        if(contador_errorVacio != 0){
            JOptionPane.showMessageDialog(null, "Ingrese los datos solicitados.");
        } else {
            try {
                Connection conexion = Conexion.conexion();
                PreparedStatement ps = conexion.prepareStatement(
                        "insert into `clientes`(`nombre_cliente`, `email_cliente`, `tel_cliente`, `dir_cliente`, `ultima_modificacion`) "
                                + "values (?,?,?,?,?)");
                
                ps.setString(1, fld_name.getText().trim());
                ps.setString(2, fld_email.getText().trim());
                ps.setString(3, fld_phone.getText().trim());
                ps.setString(4, fld_direc.getText().trim());
                ps.setString(5, Login.username);
                
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Se añadiò un nuevo cliente.");
                    
                dispose();
                conexion.close();
                
            } catch (SQLException e) {
                System.err.println("Error " + e);
            }
        }
    }//GEN-LAST:event_bttn_registroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_registro;
    private javax.swing.JTextField fld_direc;
    private javax.swing.JTextField fld_email;
    private javax.swing.JTextField fld_name;
    private javax.swing.JTextField fld_phone;
    private javax.swing.JLabel lbl_direc;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_registradoPor;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_wallpaper;
    // End of variables declaration//GEN-END:variables
}
