/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esrg.ventana;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ESRG
 */
public class RestaurarPassword extends javax.swing.JFrame {

    /**
     * Creates new form RestaurarPassword
     */
    public RestaurarPassword() {
        initComponents();
        
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Data System");
        
        ImageIcon image_wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon wallpaper = new ImageIcon(image_wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(wallpaper);
        
        lbl_user.setText(GestionarUsuario.table_update);
        
        this.repaint();
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_newPassword = new javax.swing.JLabel();
        fld_newPassword = new javax.swing.JPasswordField();
        lbl_confirmPassword = new javax.swing.JLabel();
        fld_confirmPassword = new javax.swing.JPasswordField();
        chk_password = new javax.swing.JCheckBox();
        lbl_title1 = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        bttn_resetpassword = new javax.swing.JButton();
        lbl_wallpaper = new javax.swing.JLabel();

        lbl_title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Registro de usuario");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_newPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_newPassword.setForeground(new java.awt.Color(255, 255, 255));
        lbl_newPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_newPassword.setText("Nueva contraseña");
        getContentPane().add(lbl_newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 180, -1));

        fld_newPassword.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        fld_newPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_newPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fld_newPassword.setEchoChar('\u25cf');
        getContentPane().add(fld_newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, 20));

        lbl_confirmPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_confirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        lbl_confirmPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_confirmPassword.setText("Confirmar contraseña");
        getContentPane().add(lbl_confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 180, 20));

        fld_confirmPassword.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        fld_confirmPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fld_confirmPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fld_confirmPassword.setEchoChar('\u25cf');
        getContentPane().add(fld_confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 250, 20));

        chk_password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_password.setForeground(new java.awt.Color(63, 84, 147));
        chk_password.setText("Mostrar contraseña");
        chk_password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        chk_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(chk_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        lbl_title1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_title1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title1.setText("Restaurar contraseña");
        getContentPane().add(lbl_title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lbl_user.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(255, 255, 255));
        lbl_user.setText("Usuario");
        getContentPane().add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        bttn_resetpassword.setBackground(new java.awt.Color(63, 84, 147));
        bttn_resetpassword.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bttn_resetpassword.setForeground(new java.awt.Color(255, 255, 255));
        bttn_resetpassword.setText("Restaurar contraseña");
        bttn_resetpassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttn_resetpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_resetpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_resetpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 250, 30));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_passwordActionPerformed
        if(chk_password.isSelected() == true){
            fld_newPassword.setEchoChar((char) 0);
            fld_confirmPassword.setEchoChar((char) 0);
        } else {
            fld_newPassword.setEchoChar('\u25cf');
            fld_confirmPassword.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_chk_passwordActionPerformed

    private void bttn_resetpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_resetpasswordActionPerformed
        if(fld_newPassword.getText().trim().equals("") || fld_confirmPassword.getText().trim().equals("")){
           JOptionPane.showMessageDialog(null, "Ingrese los datos solicitados");
           fld_confirmPassword.setBorder(BorderFactory.createLineBorder(new Color(180,0,0)));
           fld_newPassword.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
        } else {
           if(fld_newPassword.getText().trim().equals(fld_confirmPassword.getText().trim())){
               try {
                   Connection cn = Conexion.conexion();
                   PreparedStatement ps = cn.prepareStatement(
                           "update usuarios set password = ? where id_usuario = '" + InformacionUsuario.ID + "'");
                   ps.setString(1, fld_newPassword.getText().trim());
                   ps.executeUpdate();
                   JOptionPane.showMessageDialog(null, "Contraseña actualizada correctamente.");
                   fld_confirmPassword.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
                   fld_newPassword.setBorder(BorderFactory.createLineBorder(new Color(0,180,0), 1));
                   cn.close();
                   dispose();
               } catch (SQLException er) {
                   System.err.println("Error: " + er);
               }
           } else {
               JOptionPane.showMessageDialog(null, "Contraseña no coincide.");
               fld_confirmPassword.setBorder(BorderFactory.createLineBorder(new Color(180,0,0), 1));
           }
        }
    }//GEN-LAST:event_bttn_resetpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurarPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_resetpassword;
    private javax.swing.JCheckBox chk_password;
    private javax.swing.JPasswordField fld_confirmPassword;
    private javax.swing.JPasswordField fld_newPassword;
    private javax.swing.JLabel lbl_confirmPassword;
    private javax.swing.JLabel lbl_newPassword;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_wallpaper;
    // End of variables declaration//GEN-END:variables
}
