package esrg.ventana;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author ESRG
 */
public class Tecnico extends javax.swing.JFrame {

    /**
     * Creates new form Tecnico
     */
    public Tecnico() {
        initComponents();

        setLocationRelativeTo(null);
        setTitle("Data System | Técnico");
        setResizable(false);
        lbl_footer.setText(Login.footer);
        
        if(!Login.tipoNivel.equals("Administrador")){
            lbl_creatividad.setText("Cerrar seisón");
        } else {
            lbl_creatividad.setText("Cerrar");
        }

        if (Administrador.sesion_admin == true) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon_wallpaper = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icon_wallpaper);

        ImageIcon logo = new ImageIcon("src/images/DS.png");
        Icon icon_icon = new ImageIcon(logo.getImage().getScaledInstance(lbl_logo.getWidth(), lbl_logo.getHeight(),
                Image.SCALE_DEFAULT));
        lbl_logo.setIcon(icon_icon);

        ImageIcon cerrarSesion = new ImageIcon("src/images/cerrar_sesion.png");
        Icon icon_signoff = new ImageIcon(cerrarSesion.getImage().getScaledInstance(100, 80, Image.SCALE_DEFAULT));
        bttn_creatividad.setIcon(icon_signoff);

        lbl_username.setText("Bienvenido " + Login.nombreUsuario);
        lbl_nivel.setText(Login.tipoNivel);

        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_username = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        lbl_nivel = new javax.swing.JLabel();
        bttn_gestionEquipo = new javax.swing.JButton();
        bttn_graficaEstatus = new javax.swing.JButton();
        bttn_graficaMarcas = new javax.swing.JButton();
        lbl_footer = new javax.swing.JLabel();
        lbl_gestionEquipo = new javax.swing.JLabel();
        lbl_graficaEstatus = new javax.swing.JLabel();
        lbl_graficaMarcas = new javax.swing.JLabel();
        bttn_creatividad = new javax.swing.JButton();
        bttn_acercade = new javax.swing.JButton();
        lbl_creatividad = new javax.swing.JLabel();
        lbl_acercade = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_username.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("Hola");
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 390, -1));
        getContentPane().add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 140));

        lbl_nivel.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbl_nivel.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nivel.setText("Técnico");
        getContentPane().add(lbl_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        bttn_gestionEquipo.setBackground(new java.awt.Color(63, 84, 147));
        bttn_gestionEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apoyo-tecnico.png"))); // NOI18N
        bttn_gestionEquipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_gestionEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_gestionEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_gestionEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 120, 100));

        bttn_graficaEstatus.setBackground(new java.awt.Color(63, 84, 147));
        bttn_graficaEstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafica.png"))); // NOI18N
        bttn_graficaEstatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_graficaEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_graficaEstatusActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_graficaEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 120, 100));

        bttn_graficaMarcas.setBackground(new java.awt.Color(63, 84, 147));
        bttn_graficaMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafica.png"))); // NOI18N
        bttn_graficaMarcas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_graficaMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_graficaMarcasActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_graficaMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 120, 100));

        lbl_footer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_footer.setText("Powered by: ESRG © 2024");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 630, -1));

        lbl_gestionEquipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_gestionEquipo.setForeground(new java.awt.Color(63, 84, 147));
        lbl_gestionEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_gestionEquipo.setText("Gestión equipo");
        getContentPane().add(lbl_gestionEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 120, -1));

        lbl_graficaEstatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_graficaEstatus.setForeground(new java.awt.Color(63, 84, 147));
        lbl_graficaEstatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_graficaEstatus.setText("Gráfica estatus");
        getContentPane().add(lbl_graficaEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 140, -1));

        lbl_graficaMarcas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_graficaMarcas.setForeground(new java.awt.Color(63, 84, 147));
        lbl_graficaMarcas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_graficaMarcas.setText("Gráfica marcas");
        getContentPane().add(lbl_graficaMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 120, -1));

        bttn_creatividad.setBackground(new java.awt.Color(63, 84, 147));
        bttn_creatividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar_sesion.png"))); // NOI18N
        bttn_creatividad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_creatividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_creatividadActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_creatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 120, 100));

        bttn_acercade.setBackground(new java.awt.Color(63, 84, 147));
        bttn_acercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/geekipedia.png"))); // NOI18N
        bttn_acercade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttn_acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_acercadeActionPerformed(evt);
            }
        });
        getContentPane().add(bttn_acercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 120, 100));

        lbl_creatividad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_creatividad.setForeground(new java.awt.Color(63, 84, 147));
        lbl_creatividad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_creatividad.setText("Cerrar sesión");
        getContentPane().add(lbl_creatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 120, -1));

        lbl_acercade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_acercade.setForeground(new java.awt.Color(63, 84, 147));
        lbl_acercade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_acercade.setText("Acerca de");
        getContentPane().add(lbl_acercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 120, -1));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 640, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_gestionEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_gestionEquipoActionPerformed
        new GestionarEquipo().setVisible(true);
    }//GEN-LAST:event_bttn_gestionEquipoActionPerformed

    private void bttn_graficaEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_graficaEstatusActionPerformed
        new GraficaEstatus().setVisible(true);
    }//GEN-LAST:event_bttn_graficaEstatusActionPerformed

    private void bttn_graficaMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_graficaMarcasActionPerformed
        new GraficaMarcas().setVisible(true);
    }//GEN-LAST:event_bttn_graficaMarcasActionPerformed

    private void bttn_creatividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_creatividadActionPerformed

        if (Login.tipoNivel.equals("Administrador")) {
            dispose();
        } else {
            Frame[] ventana = Frame.getFrames();

            for (Frame frame : ventana) {
                if (frame instanceof JFrame && frame.isVisible()) {
                    frame.dispose();
                }
            }

            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_bttn_creatividadActionPerformed

    private void bttn_acercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_acercadeActionPerformed
        new AcercaDe().setVisible(true);
    }//GEN-LAST:event_bttn_acercadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_acercade;
    private javax.swing.JButton bttn_creatividad;
    private javax.swing.JButton bttn_gestionEquipo;
    private javax.swing.JButton bttn_graficaEstatus;
    private javax.swing.JButton bttn_graficaMarcas;
    private javax.swing.JLabel lbl_acercade;
    private javax.swing.JLabel lbl_creatividad;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_gestionEquipo;
    private javax.swing.JLabel lbl_graficaEstatus;
    private javax.swing.JLabel lbl_graficaMarcas;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nivel;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_wallpaper;
    // End of variables declaration//GEN-END:variables
}
